const { Client } = require('pg');

const connectionString = 'postgresql://neondb_owner:npg_wkeHO3sTxiE6@ep-rough-rice-ax0e6jfa-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require';

// ─── WORLD CAPITALS ─────────────────────────────────────────────────────────

const CAPITALS_ASIA = [
  { t:'What is the capital of Afghanistan?',       o:['Kabul','Khartoum','Yaoundé','Yerevan'],              c:0 },
  { t:'What is the capital of Armenia?',           o:['Caracas','Yerevan','Port-au-Prince','Berlin'],        c:1 },
  { t:'What is the capital of Azerbaijan?',        o:['Helsinki','Bogotá','Baku','Vatican City'],            c:2 },
  { t:'What is the capital of Bahrain?',           o:['Gitega','Lomé','Caracas','Manama'],                   c:3 },
  { t:'What is the capital of Bangladesh?',        o:['Dhaka','Doha','Brasília','Victoria'],                 c:0 },
  { t:'What is the capital of Bhutan?',            o:['Mexico City','Thimphu','Canberra','Yerevan'],         c:1 },
  { t:'What is the capital of Brunei?',            o:['Brasília','Addis Ababa','Bandar Seri Begawan','Libreville'], c:2 },
  { t:'What is the capital of Cambodia?',          o:['Islamabad','Bratislava','Buenos Aires','Phnom Penh'], c:3 },
  { t:'What is the capital of China?',             o:['Beijing','Basseterre','San Salvador','London'],       c:0 },
  { t:'What is the capital of Georgia?',           o:['Bern','Tbilisi','Funafuti','Doha'],                   c:1 },
  { t:'What is the capital of India?',             o:['Port Louis','Addis Ababa','New Delhi','Rabat'],       c:2 },
  { t:'What is the capital of Indonesia?',         o:['Belgrade','Port-au-Prince','Tirana','Jakarta'],       c:3 },
  { t:'What is the capital of Iran?',              o:['Tehran','Zagreb','Ashgabat','Mexico City'],            c:0 },
  { t:'What is the capital of Iraq?',              o:['South Tarawa','Baghdad','Port-au-Prince','San José'], c:1 },
  { t:'What is the capital of Israel?',            o:['Lobamba','Nairobi','Jerusalem','Ouagadougou'],        c:2 },
  { t:'What is the capital of Japan?',             o:['Brasília','Vilnius','Bandar Seri Begawan','Tokyo'],   c:3 },
  { t:'What is the capital of Jordan?',            o:['Amman','Riga','Kuwait City','Bratislava'],            c:0 },
  { t:'What is the capital of Kazakhstan?',        o:['Guatemala City','Astana','Nassau','Tashkent'],        c:1 },
  { t:'What is the capital of Kuwait?',            o:['Windhoek','Warsaw','Kuwait City','Praia'],            c:2 },
  { t:'What is the capital of Kyrgyzstan?',        o:['Vaduz','Sucre','Moscow','Bishkek'],                   c:3 },
  { t:'What is the capital of Laos?',              o:['Vientiane','New Delhi','Juba','Pretoria'],            c:0 },
  { t:'What is the capital of Lebanon?',           o:['Riga','Beirut','City of San Marino','Quito'],         c:1 },
  { t:'What is the capital of Malaysia?',          o:['Kampala','Belmopan','Kuala Lumpur','Nassau'],         c:2 },
  { t:'What is the capital of the Maldives?',      o:['Dushanbe','Helsinki','Reykjavik','Malé'],             c:3 },
  { t:'What is the capital of Mongolia?',          o:['Ulan Bator','Sucre','Paris','Sofia'],                 c:0 },
  { t:'What is the capital of Myanmar?',           o:['Vaduz','Naypyidaw','Port-au-Prince','Maputo'],        c:1 },
  { t:'What is the capital of Nepal?',             o:['Sri Jayawardenepura Kotte','Beirut','Kathmandu','Havana'], c:2 },
  { t:'What is the capital of North Korea?',       o:['Maseru','Bishkek','Asmara','Pyongyang'],              c:3 },
  { t:'What is the capital of Oman?',              o:['Muscat','Bangkok','Conakry','Funafuti'],              c:0 },
  { t:'What is the capital of Pakistan?',          o:['Nuku\'alofa','Islamabad','Stockholm','Porto-Novo'],   c:1 },
  { t:'What is the capital of Palestine?',         o:['Ljubljana','Sri Jayawardenepura Kotte','Ramallah','Prague'], c:2 },
  { t:'What is the capital of the Philippines?',   o:['Lima','Tashkent','Tbilisi','Manila'],                 c:3 },
  { t:'What is the capital of Qatar?',             o:['Doha','Havana','Windhoek','Vaduz'],                   c:0 },
  { t:'What is the capital of Saudi Arabia?',      o:['Bissau','Riyadh','Khartoum','Tunis'],                 c:1 },
  { t:'What is the capital of Singapore?',         o:['Moscow','Addis Ababa','Singapore','Port of Spain'],   c:2 },
  { t:'What is the capital of South Korea?',       o:['Kingston','Bridgetown','Helsinki','Seoul'],           c:3 },
  { t:'What is the capital of Sri Lanka?',         o:['Sri Jayawardenepura Kotte','Canberra','Jerusalem','Kuala Lumpur'], c:0 },
  { t:'What is the capital of Syria?',             o:['Conakry','Damascus','Brussels','Tallinn'],            c:1 },
  { t:'What is the capital of Tajikistan?',        o:['Castries','London','Dushanbe','Jerusalem'],           c:2 },
  { t:'What is the capital of Thailand?',          o:['Tallinn','Bern','Skopje','Bangkok'],                  c:3 },
  { t:'What is the capital of Timor-Leste?',       o:['Dili','Lilongwe','Khartoum','Naypyidaw'],             c:0 },
  { t:'What is the capital of Turkey?',            o:['Bogotá','Ankara','Guatemala City','Beijing'],          c:1 },
  { t:'What is the capital of Turkmenistan?',      o:['Berlin','Hanoi','Ashgabat','Kigali'],                 c:2 },
  { t:'What is the capital of the United Arab Emirates?', o:['Manila','Guatemala City','Sana\'a','Abu Dhabi'], c:3 },
  { t:'What is the capital of Uzbekistan?',        o:['Tashkent','Riyadh','Mexico City','Kuala Lumpur'],     c:0 },
  { t:'What is the capital of Vietnam?',           o:['Riga','Hanoi','Addis Ababa','Beijing'],               c:1 },
  { t:'What is the capital of Yemen?',             o:['Islamabad','Pyongyang','Sana\'a','Brasília'],         c:2 },
];

const CAPITALS_AFRICA = [
  { t:'What is the capital of Algeria?',                    o:['Harare','Dhaka','Yaoundé','Algiers'],                c:3 },
  { t:'What is the capital of Angola?',                     o:['Luanda','Zagreb','Juba','Havana'],                   c:0 },
  { t:'What is the capital of Benin?',                      o:['Nuku\'alofa','Porto-Novo','Mexico City','Freetown'], c:1 },
  { t:'What is the capital of Botswana?',                   o:['Brussels','Luxembourg','Gaborone','Vilnius'],        c:2 },
  { t:'What is the capital of Burkina Faso?',               o:['Freetown','Kathmandu','Lima','Ouagadougou'],         c:3 },
  { t:'What is the capital of Burundi?',                    o:['Gitega','Athens','Moscow','Algiers'],                c:0 },
  { t:'What is the capital of Cameroon?',                   o:['Nuku\'alofa','Yaoundé','Washington D.C.','Ottawa'],  c:1 },
  { t:'What is the capital of Cape Verde?',                 o:['Nuku\'alofa','Warsaw','Praia','Lusaka'],             c:2 },
  { t:'What is the capital of the Central African Republic?', o:['Bissau','Paramaribo','South Tarawa','Bangui'],     c:3 },
  { t:'What is the capital of Chad?',                       o:['N\'Djamena','Phnom Penh','Jakarta','Monaco'],        c:0 },
  { t:'What is the capital of the Comoros?',                o:['Havana','Moroni','Naypyidaw','Kabul'],               c:1 },
  { t:'What is the capital of Congo?',                      o:['Washington D.C.','Conakry','Brazzaville','Muscat'],  c:2 },
  { t:'What is the capital of the Democratic Republic of the Congo?', o:['Djibouti','Islamabad','Gitega','Kinshasa'], c:3 },
  { t:'What is the capital of Djibouti?',                   o:['Djibouti','Juba','Tehran','Khartoum'],              c:0 },
  { t:'What is the capital of Egypt?',                      o:['Islamabad','Cairo','Ljubljana','San Salvador'],      c:1 },
  { t:'What is the capital of Equatorial Guinea?',          o:['San José','Tripoli','Malabo','Havana'],              c:2 },
  { t:'What is the capital of Eritrea?',                    o:['Lisbon','Lima','Kabul','Asmara'],                    c:3 },
  { t:'What is the capital of Eswatini?',                   o:['Lobamba','Singapore','Kingston','Pyongyang'],        c:0 },
  { t:'What is the capital of Ethiopia?',                   o:['Luanda','Addis Ababa','Phnom Penh','Beirut'],        c:1 },
  { t:'What is the capital of Gabon?',                      o:['Dublin','Tbilisi','Libreville','Bridgetown'],        c:2 },
  { t:'What is the capital of the Gambia?',                 o:['Tbilisi','Kingstown','Sucre','Banjul'],              c:3 },
  { t:'What is the capital of Ghana?',                      o:['Accra','Sarajevo','Port Vila','Abuja'],              c:0 },
  { t:'What is the capital of Guinea?',                     o:['Belmopan','Conakry','Manila','Bangui'],              c:1 },
  { t:'What is the capital of Guinea-Bissau?',              o:['Bangui','São Tomé','Bissau','Wellington'],           c:2 },
  { t:'What is the capital of Ivory Coast (Cote d\'Ivoire)?', o:['Bucharest','Nicosia','Guatemala City','Yamoussoukro'], c:3 },
  { t:'What is the capital of Kenya?',                      o:['Nairobi','Lima','Ljubljana','Mexico City'],          c:0 },
  { t:'What is the capital of Lesotho?',                    o:['Tallinn','Maseru','Lisbon','Harare'],                c:1 },
  { t:'What is the capital of Liberia?',                    o:['Tashkent','Tunis','Monrovia','San Salvador'],        c:2 },
  { t:'What is the capital of Libya?',                      o:['Abu Dhabi','Dublin','Malé','Tripoli'],               c:3 },
  { t:'What is the capital of Madagascar?',                 o:['Antananarivo','Bangkok','Bern','Monrovia'],          c:0 },
  { t:'What is the capital of Malawi?',                     o:['Ulan Bator','Lilongwe','Panama City','Maputo'],      c:1 },
  { t:'What is the capital of Mali?',                       o:['Ottawa','Berlin','Bamako','Suva'],                   c:2 },
  { t:'What is the capital of Mauritania?',                 o:['Brussels','Astana','Saint John\'s','Nouakchott'],    c:3 },
  { t:'What is the capital of Mauritius?',                  o:['Port Louis','Belgrade','Moscow','Helsinki'],         c:0 },
  { t:'What is the capital of Morocco?',                    o:['Belgrade','Rabat','Addis Ababa','Tirana'],           c:1 },
  { t:'What is the capital of Mozambique?',                 o:['Porto-Novo','Kyiv','Maputo','Madrid'],               c:2 },
  { t:'What is the capital of Namibia?',                    o:['Minsk','Helsinki','Belmopan','Windhoek'],            c:3 },
  { t:'What is the capital of Niger?',                      o:['Niamey','Canberra','Tokyo','Porto-Novo'],            c:0 },
  { t:'What is the capital of Nigeria?',                    o:['Ramallah','Abuja','Libreville','Port-au-Prince'],    c:1 },
  { t:'What is the capital of Rwanda?',                     o:['Bangkok','Niamey','Kigali','Tallinn'],               c:2 },
  { t:'What is the capital of Senegal?',                    o:['Warsaw','N\'Djamena','Montevideo','Dakar'],          c:3 },
  { t:'What is the capital of Seychelles?',                 o:['Victoria','Kingstown','Apia','Amsterdam'],           c:0 },
  { t:'What is the capital of Sierra Leone?',               o:['Tbilisi','Freetown','Amsterdam','Bamako'],           c:1 },
  { t:'What is the capital of Somalia?',                    o:['Santo Domingo','Bandar Seri Begawan','Mogadishu','São Tomé'], c:2 },
  { t:'What is the capital of South Africa?',               o:['Palikir','Bishkek','Port Louis','Pretoria'],         c:3 },
  { t:'What is the capital of South Sudan?',                o:['Juba','Valletta','Yaren','Tashkent'],                c:0 },
  { t:'What is the capital of Sudan?',                      o:['Dhaka','Khartoum','Dili','Damascus'],                c:1 },
  { t:'What is the capital of São Tomé and Príncipe?',      o:['Paramaribo','Sofia','São Tomé','Minsk'],             c:2 },
  { t:'What is the capital of Tanzania?',                   o:['Malé','Tashkent','Astana','Dodoma'],                 c:3 },
  { t:'What is the capital of Togo?',                       o:['Lomé','Gitega','Berlin','Quito'],                    c:0 },
  { t:'What is the capital of Tunisia?',                    o:['Santo Domingo','Tunis','Manila','Podgorica'],        c:1 },
  { t:'What is the capital of Uganda?',                     o:['Beijing','Port Louis','Kampala','Djibouti'],         c:2 },
  { t:'What is the capital of Zambia?',                     o:['Port-au-Prince','Windhoek','Berlin','Lusaka'],       c:3 },
  { t:'What is the capital of Zimbabwe?',                   o:['Harare','Thimphu','Ulan Bator','Doha'],              c:0 },
];

const CAPITALS_EUROPE = [
  { t:'What is the capital of Albania?',              o:['Ouagadougou','Tirana','Dhaka','Bern'],                c:1 },
  { t:'What is the capital of Andorra?',              o:['Lisbon','Luanda','Andorra la Vella','Bandar Seri Begawan'], c:2 },
  { t:'What is the capital of Austria?',              o:['Lusaka','Banjul','Prague','Vienna'],                  c:3 },
  { t:'What is the capital of Belarus?',              o:['Minsk','Valletta','Abuja','Niamey'],                  c:0 },
  { t:'What is the capital of Belgium?',              o:['Lobamba','Brussels','Malé','Minsk'],                  c:1 },
  { t:'What is the capital of Bosnia and Herzegovina?', o:['Prague','Vilnius','Sarajevo','Kabul'],              c:2 },
  { t:'What is the capital of Bulgaria?',             o:['Antananarivo','Conakry','Naypyidaw','Sofia'],         c:3 },
  { t:'What is the capital of Croatia?',              o:['Zagreb','Reykjavik','Mexico City','Ashgabat'],        c:0 },
  { t:'What is the capital of Cyprus?',               o:['Port Vila','Nicosia','Kigali','Dushanbe'],            c:1 },
  { t:'What is the capital of the Czech Republic?',   o:['London','Abuja','Prague','San José'],                 c:2 },
  { t:'What is the capital of Denmark?',              o:['Quito','Jakarta','Addis Ababa','Copenhagen'],         c:3 },
  { t:'What is the capital of Estonia?',              o:['Tallinn','Bridgetown','Riyadh','Vatican City'],        c:0 },
  { t:'What is the capital of Finland?',              o:['Lisbon','Helsinki','Minsk','Sana\'a'],                c:1 },
  { t:'What is the capital of France?',               o:['Rome','Bridgetown','Paris','Manama'],                 c:2 },
  { t:'What is the capital of Germany?',              o:['Dakar','Managua','Muscat','Berlin'],                  c:3 },
  { t:'What is the capital of Greece?',               o:['Athens','Lima','Zagreb','Bridgetown'],                c:0 },
  { t:'What is the capital of Hungary?',              o:['Ngerulmud','Budapest','Sucre','Roseau'],              c:1 },
  { t:'What is the capital of Iceland?',              o:['Belmopan','Freetown','Reykjavik','Dili'],             c:2 },
  { t:'What is the capital of Ireland?',              o:['Libreville','Bamako','Ottawa','Dublin'],              c:3 },
  { t:'What is the capital of Italy?',                o:['Rome','Kingstown','Berlin','Riyadh'],                 c:0 },
  { t:'What is the capital of Latvia?',               o:['Freetown','Riga','Baku','Pretoria'],                  c:1 },
  { t:'What is the capital of Liechtenstein?',        o:['Sucre','Port Louis','Vaduz','São Tomé'],              c:2 },
  { t:'What is the capital of Lithuania?',            o:['Dakar','Castries','Port Moresby','Vilnius'],          c:3 },
  { t:'What is the capital of Luxembourg?',           o:['Luxembourg','Jerusalem','St. George\'s','Malabo'],   c:0 },
  { t:'What is the capital of Malta?',                o:['Bangkok','Valletta','London','Jerusalem'],            c:1 },
  { t:'What is the capital of Moldova?',              o:['Banjul','Guatemala City','Chișinău','Lilongwe'],      c:2 },
  { t:'What is the capital of Monaco?',               o:['N\'Djamena','Bangkok','Stockholm','Monaco'],          c:3 },
  { t:'What is the capital of Montenegro?',           o:['Podgorica','Jakarta','Windhoek','Jerusalem'],         c:0 },
  { t:'What is the capital of the Netherlands?',      o:['Lusaka','Amsterdam','Porto-Novo','Algiers'],          c:1 },
  { t:'What is the capital of North Macedonia?',      o:['Naypyidaw','Seoul','Skopje','Castries'],              c:2 },
  { t:'What is the capital of Norway?',               o:['Sofia','Porto-Novo','Warsaw','Oslo'],                 c:3 },
  { t:'What is the capital of Poland?',               o:['Warsaw','Tallinn','Muscat','Guatemala City'],         c:0 },
  { t:'What is the capital of Portugal?',             o:['N\'Djamena','Lisbon','Kuwait City','Belmopan'],      c:1 },
  { t:'What is the capital of Romania?',              o:['Tbilisi','Maseru','Bucharest','Tegucigalpa'],         c:2 },
  { t:'What is the capital of Russia?',               o:['Zagreb','Monaco','Lisbon','Moscow'],                  c:3 },
  { t:'What is the capital of San Marino?',           o:['City of San Marino','Kampala','Tehran','Honiara'],   c:0 },
  { t:'What is the capital of Serbia?',               o:['Damascus','Belgrade','Asunción','Algiers'],           c:1 },
  { t:'What is the capital of Slovakia?',             o:['Dodoma','Bucharest','Bratislava','Jakarta'],          c:2 },
  { t:'What is the capital of Slovenia?',             o:['Dushanbe','Ouagadougou','Santiago','Ljubljana'],      c:3 },
  { t:'What is the capital of Spain?',                o:['Madrid','Guatemala City','Yaoundé','Gitega'],         c:0 },
  { t:'What is the capital of Sweden?',               o:['Hanoi','Stockholm','Bucharest','San José'],           c:1 },
  { t:'What is the capital of Switzerland?',          o:['Bissau','Tegucigalpa','Bern','Singapore'],            c:2 },
  { t:'What is the capital of Ukraine?',              o:['Asmara','London','Nairobi','Kyiv'],                   c:3 },
  { t:'What is the capital of the United Kingdom?',   o:['London','Malabo','Nuku\'alofa','Madrid'],             c:0 },
  { t:'What is the capital of Vatican City (Holy See)?', o:['Guatemala City','Vatican City','Muscat','Abuja'], c:1 },
];

const CAPITALS_AMERICAS = [
  { t:'What is the capital of Antigua and Barbuda?',           o:['Athens','Bridgetown','Saint John\'s','Bandar Seri Begawan'], c:2 },
  { t:'What is the capital of Argentina?',                     o:['Sri Jayawardenepura Kotte','Mexico City','Port-au-Prince','Buenos Aires'], c:3 },
  { t:'What is the capital of the Bahamas?',                   o:['Nassau','Manama','Kabul','Astana'],                  c:0 },
  { t:'What is the capital of Barbados?',                      o:['Santiago','Bridgetown','Khartoum','Conakry'],         c:1 },
  { t:'What is the capital of Belize?',                        o:['Nicosia','Caracas','Belmopan','Podgorica'],           c:2 },
  { t:'What is the capital of Bolivia?',                       o:['Moscow','Kampala','Palikir','Sucre'],                 c:3 },
  { t:'What is the capital of Brazil?',                        o:['Brasília','Basseterre','Algiers','Yaoundé'],          c:0 },
  { t:'What is the capital of Canada?',                        o:['Thimphu','Ottawa','Tunis','San José'],                c:1 },
  { t:'What is the capital of Chile?',                         o:['Doha','Vienna','Santiago','Monrovia'],                c:2 },
  { t:'What is the capital of Colombia?',                      o:['Dakar','Moscow','Brazzaville','Bogotá'],              c:3 },
  { t:'What is the capital of Costa Rica?',                    o:['San José','Chișinău','Bangui','Baku'],                c:0 },
  { t:'What is the capital of Cuba?',                          o:['Dublin','Havana','Maseru','Baku'],                    c:1 },
  { t:'What is the capital of Dominica?',                      o:['Riga','Tallinn','Roseau','Nuku\'alofa'],              c:2 },
  { t:'What is the capital of the Dominican Republic?',        o:['Accra','Dodoma','Ouagadougou','Santo Domingo'],       c:3 },
  { t:'What is the capital of Ecuador?',                       o:['Quito','Vientiane','Basseterre','Valletta'],          c:0 },
  { t:'What is the capital of El Salvador?',                   o:['Pretoria','San Salvador','Sana\'a','San José'],       c:1 },
  { t:'What is the capital of Grenada?',                       o:['Libreville','Havana','St. George\'s','Copenhagen'],  c:2 },
  { t:'What is the capital of Guatemala?',                     o:['Majuro','Buenos Aires','Copenhagen','Guatemala City'], c:3 },
  { t:'What is the capital of Guyana?',                        o:['Georgetown','Vatican City','Astana','Majuro'],        c:0 },
  { t:'What is the capital of Haiti?',                         o:['Bangkok','Port-au-Prince','Vatican City','Berlin'],   c:1 },
  { t:'What is the capital of Honduras?',                      o:['Conakry','Zagreb','Tegucigalpa','Funafuti'],          c:2 },
  { t:'What is the capital of Jamaica?',                       o:['Gitega','Vilnius','Vienna','Kingston'],               c:3 },
  { t:'What is the capital of Mexico?',                        o:['Mexico City','Amsterdam','Addis Ababa','San Salvador'], c:0 },
  { t:'What is the capital of Nicaragua?',                     o:['Naypyidaw','Managua','Kuwait City','Baghdad'],        c:1 },
  { t:'What is the capital of Panama?',                        o:['Helsinki','Suva','Panama City','Buenos Aires'],       c:2 },
  { t:'What is the capital of Paraguay?',                      o:['São Tomé','Quito','Kuala Lumpur','Asunción'],         c:3 },
  { t:'What is the capital of Peru?',                          o:['Lima','Tokyo','Port-au-Prince','Belmopan'],           c:0 },
  { t:'What is the capital of Saint Kitts and Nevis?',         o:['Port-au-Prince','Basseterre','Kuwait City','Paramaribo'], c:1 },
  { t:'What is the capital of Saint Lucia?',                   o:['Islamabad','Kuala Lumpur','Castries','Lomé'],         c:2 },
  { t:'What is the capital of Saint Vincent and the Grenadines?', o:['Manila','Tokyo','Yerevan','Kingstown'],             c:3 },
  { t:'What is the capital of Suriname?',                      o:['Paramaribo','Yaoundé','St. George\'s','Copenhagen'], c:0 },
  { t:'What is the capital of Trinidad and Tobago?',           o:['City of San Marino','Port of Spain','Guatemala City','Vienna'], c:1 },
  { t:'What is the capital of the United States?',             o:['Gitega','Victoria','Washington D.C.','Chișinău'],     c:2 },
  { t:'What is the capital of Uruguay?',                       o:['South Tarawa','Tashkent','Jerusalem','Montevideo'],   c:3 },
  { t:'What is the capital of Venezuela?',                     o:['Caracas','Chișinău','Bratislava','Islamabad'],        c:0 },
];

const CAPITALS_OCEANIA = [
  { t:'What is the capital of Australia?',           o:['Ottawa','Canberra','Luxembourg','City of San Marino'], c:1 },
  { t:'What is the capital of Fiji?',                o:['Santo Domingo','St. George\'s','Suva','Nassau'],        c:2 },
  { t:'What is the capital of Kiribati?',            o:['Kyiv','Monaco','Kabul','South Tarawa'],                 c:3 },
  { t:'What is the capital of the Marshall Islands?', o:['Majuro','Port Moresby','Warsaw','Port of Spain'],      c:0 },
  { t:'What is the capital of Micronesia?',          o:['Washington D.C.','Palikir','Caracas','Vatican City'],   c:1 },
  { t:'What is the capital of Nauru?',               o:['Bangkok','Cairo','Yaren','Beirut'],                     c:2 },
  { t:'What is the capital of New Zealand?',         o:['Palikir','Belmopan','Dodoma','Wellington'],             c:3 },
  { t:'What is the capital of Palau?',               o:['Ngerulmud','Tokyo','Seoul','Jerusalem'],                c:0 },
  { t:'What is the capital of Papua New Guinea?',    o:['Dushanbe','Port Moresby','Praia','Washington D.C.'],    c:1 },
  { t:'What is the capital of Samoa?',               o:['Jakarta','Muscat','Apia','Dublin'],                     c:2 },
  { t:'What is the capital of the Solomon Islands?', o:['Dodoma','Bamako','Kingston','Honiara'],                 c:3 },
  { t:'What is the capital of Tonga?',               o:['Nuku\'alofa','Malé','Ashgabat','New Delhi'],            c:0 },
  { t:'What is the capital of Tuvalu?',              o:['Bucharest','Funafuti','Bangui','Quito'],                 c:1 },
  { t:'What is the capital of Vanuatu?',             o:['Nouakchott','Dushanbe','Port Vila','Vaduz'],             c:2 },
];

// ─── WORLD CURRENCIES ────────────────────────────────────────────────────────

const CURRENCIES_ASIA = [
  { t:'What is the official currency of Afghanistan?',    o:['Afghan afghani','Fijian dollar','Mexican peso','Serbian dinar'], c:0 },
  { t:'What is the official currency of Armenia?',        o:['Zimbabwe Gold','Armenian dram','Afghan afghani','Mexican peso'], c:1 },
  { t:'What is the official currency of Azerbaijan?',     o:['Malaysian ringgit','Indian rupee','Azerbaijani manat','South Korean won'], c:2 },
  { t:'What is the official currency of Bahrain?',        o:['Namibian dollar','São Tomé dobra','Sudanese pound','Bahraini dinar'], c:3 },
  { t:'What is the official currency of Bangladesh?',     o:['Bangladeshi taka','Sudanese pound','Indonesian rupiah','UAE dirham'], c:0 },
  { t:'What is the official currency of Bhutan?',         o:['Tanzanian shilling','Bhutanese ngultrum','Euro','Burundian franc'], c:1 },
  { t:'What is the official currency of Brunei?',         o:['Malawian kwacha','United States dollar','Brunei dollar','Nicaraguan córdoba'], c:2 },
  { t:'What is the official currency of Cambodia?',       o:['Canadian dollar','Jordanian dinar','Mongolian tögrög','Cambodian riel'], c:3 },
  { t:'What is the official currency of China?',          o:['Chinese yuan','Israeli new shekel','Honduran lempira','Djiboutian franc'], c:0 },
  { t:'What is the official currency of Georgia?',        o:['Australian dollar','Lari','Barbadian dollar','Kazakhstani tenge'], c:1 },
  { t:'What is the official currency of India?',          o:['Tanzanian shilling','Brazilian real','Indian rupee','Swedish krona'], c:2 },
  { t:'What is the official currency of Indonesia?',      o:['Singapore dollar','Guyanese dollar','Romanian leu','Indonesian rupiah'], c:3 },
  { t:'What is the official currency of Iran?',           o:['Iranian rial','Turkish lira','Saudi riyal','Kenyan shilling'], c:0 },
  { t:'What is the official currency of Iraq?',           o:['Denar','Iraqi dinar','Albanian lek','Chilean peso'], c:1 },
  { t:'What is the official currency of Israel?',         o:['Somali shilling','Iranian rial','Israeli new shekel','Fijian dollar'], c:2 },
  { t:'What is the official currency of Japan?',          o:['Uruguayan peso','Syrian pound','Belarusian ruble','Japanese yen'], c:3 },
  { t:'What is the official currency of Jordan?',         o:['Jordanian dinar','Kuwaiti dinar','Congolese franc','Swedish krona'], c:0 },
  { t:'What is the official currency of Kazakhstan?',     o:['Czech koruna','Kazakhstani tenge','Syrian pound','Venezuelan bolívar'], c:1 },
  { t:'What is the official currency of Kuwait?',         o:['Mozambican metical','Sudanese pound','Kuwaiti dinar','Ukrainian hryvnia'], c:2 },
  { t:'What is the official currency of Kyrgyzstan?',     o:['South African rand','Zimbabwe Gold','Surinamese dollar','Kyrgyzstani som'], c:3 },
  { t:'What is the official currency of Laos?',           o:['Lao kip','Eastern Caribbean dollar','Tanzanian shilling','Swazi lilangeni'], c:0 },
  { t:'What is the official currency of Lebanon?',        o:['Lao kip','Lebanese pound','Kenyan shilling','Libyan dinar'], c:1 },
  { t:'What is the official currency of Malaysia?',       o:['Uzbekistani soʻm','Trinidad and Tobago dollar','Malaysian ringgit','Jordanian dinar'], c:2 },
  { t:'What is the official currency of the Maldives?',   o:['Liberian dollar','Sri Lankan rupee','British pound','Maldivian rufiyaa'], c:3 },
  { t:'What is the official currency of Mongolia?',       o:['Mongolian tögrög','Malawian kwacha','Japanese yen','Lesotho loti'], c:0 },
  { t:'What is the official currency of Myanmar?',        o:['Nicaraguan córdoba','Burmese kyat','Mozambican metical','Yemeni rial'], c:1 },
  { t:'What is the official currency of Nepal?',          o:['Brunei dollar','Dalasi','Nepalese rupee','Djiboutian franc'], c:2 },
  { t:'What is the official currency of North Korea?',    o:['Jamaican dollar','Romanian leu','Dominican peso','North Korean won'], c:3 },
  { t:'What is the official currency of Oman?',           o:['Omani rial','Indian rupee','Bosnia convertible mark','Singapore dollar'], c:0 },
  { t:'What is the official currency of Pakistan?',       o:['Seychellois rupee','Pakistani rupee','Nepalese rupee','Yemeni rial'], c:1 },
  { t:'What is the official currency of Palestine?',      o:['São Tomé dobra','Singapore dollar','Israeli new shekel','Bolivian boliviano'], c:2 },
  { t:'What is the official currency of the Philippines?', o:['Hungarian forint','Solomon Islands dollar','Russian ruble','Philippine peso'], c:3 },
  { t:'What is the official currency of Qatar?',          o:['Qatari riyal','Armenian dram','Polish złoty','Thai baht'], c:0 },
  { t:'What is the official currency of Saudi Arabia?',   o:['Albanian lek','Saudi riyal','Omani rial','Mauritanian ouguiya'], c:1 },
  { t:'What is the official currency of Singapore?',      o:['Romanian leu','Solomon Islands dollar','Singapore dollar','West African CFA franc'], c:2 },
  { t:'What is the official currency of South Korea?',    o:['Zambian kwacha','Iranian rial','Trinidad and Tobago dollar','South Korean won'], c:3 },
  { t:'What is the official currency of Sri Lanka?',      o:['Sri Lankan rupee','Iranian rial','Lesotho loti','South Korean won'], c:0 },
  { t:'What is the official currency of Syria?',          o:['Trinidad and Tobago dollar','Syrian pound','Azerbaijani manat','Romanian leu'], c:1 },
  { t:'What is the official currency of Tajikistan?',     o:['Nicaraguan córdoba','Saudi riyal','Tajikistani somoni','Eritrean nakfa'], c:2 },
  { t:'What is the official currency of Thailand?',       o:['Syrian pound','Costa Rican colón','Vietnamese đồng','Thai baht'], c:3 },
  { t:'What is the official currency of Timor-Leste?',    o:['United States dollar','Australian dollar','Russian ruble','Burmese kyat'], c:0 },
  { t:'What is the official currency of Turkey?',         o:['Somali shilling','Turkish lira','Czech koruna','Swiss franc'], c:1 },
  { t:'What is the official currency of Turkmenistan?',   o:['Ghanaian cedi','Belarusian ruble','Turkmenistan manat','Lao kip'], c:2 },
  { t:'What is the official currency of the United Arab Emirates?', o:['Polish złoty','Namibian dollar','Indian rupee','UAE dirham'], c:3 },
  { t:'What is the official currency of Uzbekistan?',     o:['Uzbekistani soʻm','Swazi lilangeni','Namibian dollar','Nicaraguan córdoba'], c:0 },
  { t:'What is the official currency of Vietnam?',        o:['Polish złoty','Vietnamese đồng','Libyan dinar','Singapore dollar'], c:1 },
  { t:'What is the official currency of Yemen?',          o:['Kuwaiti dinar','Brunei dollar','Yemeni rial','São Tomé dobra'], c:2 },
];

const CURRENCIES_AFRICA = [
  { t:'What is the official currency of Algeria?',       o:['Armenian dram','Yemeni rial','Bhutanese ngultrum','Algerian dinar'], c:3 },
  { t:'What is the official currency of Angola?',        o:['Angolan kwanza','Omani rial','Israeli new shekel','Brazilian real'], c:0 },
  { t:'What is the official currency of Benin?',         o:['Bangladeshi taka','West African CFA franc','Azerbaijani manat','Kenyan shilling'], c:1 },
  { t:'What is the official currency of Botswana?',      o:['Hungarian forint','Armenian dram','Botswana pula','Eastern Caribbean dollar'], c:2 },
  { t:'What is the official currency of Burkina Faso?',  o:['Jordanian dinar','Costa Rican colón','Tajikistani somoni','West African CFA franc'], c:3 },
  { t:'What is the official currency of Burundi?',       o:['Burundian franc','Comorian franc','Iranian rial','São Tomé dobra'], c:0 },
  { t:'What is the official currency of Cameroon?',      o:['Lao kip','Central African CFA franc','Peruvian sol','Ethiopian birr'], c:1 },
  { t:'What is the official currency of Cape Verde?',    o:['Comorian franc','Eritrean nakfa','Cape Verdean escudo','Mongolian tögrög'], c:2 },
  { t:'What is the official currency of the Central African Republic?', o:['Chinese yuan','Australian dollar','Mongolian tögrög','Central African CFA franc'], c:3 },
  { t:'What is the official currency of Chad?',          o:['Central African CFA franc','Polish złoty','Samoan tālā','Honduran lempira'], c:0 },
  { t:'What is the official currency of the Comoros?',   o:['British pound','Comorian franc','Kenyan shilling','Central African CFA franc'], c:1 },
  { t:'What is the official currency of Congo?',         o:['Mexican peso','Congolese franc','Central African CFA franc','Bangladeshi taka'], c:2 },
  { t:'What is the official currency of the Democratic Republic of the Congo?', o:['Norwegian krone','Vietnamese đồng','South African rand','Congolese franc'], c:3 },
  { t:'What is the official currency of Djibouti?',      o:['Djiboutian franc','Peruvian sol','Botswana pula','Ukrainian hryvnia'], c:0 },
  { t:'What is the official currency of Egypt?',         o:['North Korean won','Egyptian pound','Angolan kwanza','Solomon Islands dollar'], c:1 },
  { t:'What is the official currency of Equatorial Guinea?', o:['Tunisian dinar','Chinese yuan','Central African CFA franc','South Korean won'], c:2 },
  { t:'What is the official currency of Eritrea?',       o:['Papua New Guinean kina','Swiss franc','Dominican peso','Eritrean nakfa'], c:3 },
  { t:'What is the official currency of Eswatini?',      o:['Swazi lilangeni','South Korean won','Fijian dollar','Uzbekistani soʻm'], c:0 },
  { t:'What is the official currency of Ethiopia?',      o:['Liberian dollar','Ethiopian birr','West African CFA franc','Tongan paʻanga'], c:1 },
  { t:'What is the official currency of Gabon?',         o:['São Tomé dobra','South Sudanese pound','Central African CFA franc','Lesotho loti'], c:2 },
  { t:'What is the official currency of the Gambia?',    o:['Namibian dollar','Kenyan shilling','Burundian franc','Dalasi'], c:3 },
  { t:'What is the official currency of Ghana?',         o:['Ghanaian cedi','Malagasy ariary','Swazi lilangeni','Kenyan shilling'], c:0 },
  { t:'What is the official currency of Guinea?',        o:['Syrian pound','Guinean franc','Qatari riyal','Nigerian naira'], c:1 },
  { t:'What is the official currency of Guinea-Bissau?', o:['Azerbaijani manat','Tunisian dinar','West African CFA franc','Namibian dollar'], c:2 },
  { t:'What is the official currency of Ivory Coast (Cote d\'Ivoire)?', o:['Ghanaian cedi','Tongan paʻanga','Indian rupee','West African CFA franc'], c:3 },
  { t:'What is the official currency of Kenya?',         o:['Kenyan shilling','Pakistani rupee','Lari','North Korean won'], c:0 },
  { t:'What is the official currency of Lesotho?',       o:['Malagasy ariary','Lesotho loti','Libyan dinar','Algerian dinar'], c:1 },
  { t:'What is the official currency of Liberia?',       o:['Uruguayan peso','Guinean franc','Liberian dollar','Burmese kyat'], c:2 },
  { t:'What is the official currency of Libya?',         o:['Jordanian dinar','Seychellois rupee','Tunisian dinar','Libyan dinar'], c:3 },
  { t:'What is the official currency of Madagascar?',    o:['Malagasy ariary','Jordanian dinar','Tanzanian shilling','Tunisian dinar'], c:0 },
  { t:'What is the official currency of Malawi?',        o:['Surinamese dollar','Malawian kwacha','Argentine peso','Cambodian riel'], c:1 },
  { t:'What is the official currency of Mali?',          o:['Maldivian rufiyaa','Iranian rial','West African CFA franc','Saudi riyal'], c:2 },
  { t:'What is the official currency of Mauritania?',    o:['Kazakhstani tenge','Moldovan leu','Peruvian sol','Mauritanian ouguiya'], c:3 },
  { t:'What is the official currency of Mauritius?',     o:['Mauritian rupee','Tanzanian shilling','Venezuelan bolívar','Norwegian krone'], c:0 },
  { t:'What is the official currency of Morocco?',       o:['Somali shilling','Moroccan dirham','Zimbabwe Gold','New Zealand dollar'], c:1 },
  { t:'What is the official currency of Mozambique?',    o:['Pakistani rupee','Swedish krona','Mozambican metical','Lesotho loti'], c:2 },
  { t:'What is the official currency of Namibia?',       o:['Mexican peso','Kuwaiti dinar','Jamaican dollar','Namibian dollar'], c:3 },
  { t:'What is the official currency of Niger?',         o:['West African CFA franc','Comorian franc','Guyanese dollar','Mongolian tögrög'], c:0 },
  { t:'What is the official currency of Nigeria?',       o:['Comorian franc','Nigerian naira','West African CFA franc','Guatemalan quetzal'], c:1 },
  { t:'What is the official currency of Rwanda?',        o:['Guyanese dollar','Indonesian rupiah','Rwandan franc','Tongan paʻanga'], c:2 },
  { t:'What is the official currency of Senegal?',       o:['Liberian dollar','Uzbekistani soʻm','Malagasy ariary','West African CFA franc'], c:3 },
  { t:'What is the official currency of Seychelles?',    o:['Seychellois rupee','Cape Verdean escudo','Guyanese dollar','Maldivian rufiyaa'], c:0 },
  { t:'What is the official currency of Sierra Leone?',  o:['Israeli new shekel','Sierra Leonean leone','Panamanian balboa','Fijian dollar'], c:1 },
  { t:'What is the official currency of Somalia?',       o:['Mauritian rupee','Angolan kwanza','Somali shilling','Vietnamese đồng'], c:2 },
  { t:'What is the official currency of South Africa?',  o:['Costa Rican colón','Liberian dollar','Barbadian dollar','South African rand'], c:3 },
  { t:'What is the official currency of South Sudan?',   o:['South Sudanese pound','Belize dollar','Malaysian ringgit','Costa Rican colón'], c:0 },
  { t:'What is the official currency of Sudan?',         o:['Tunisian dinar','Sudanese pound','Central African CFA franc','Angolan kwanza'], c:1 },
  { t:'What is the official currency of São Tomé and Príncipe?', o:['Malagasy ariary','Tajikistani somoni','São Tomé dobra','Thai baht'], c:2 },
  { t:'What is the official currency of Tanzania?',      o:['South Sudanese pound','Nigerian naira','Guatemalan quetzal','Tanzanian shilling'], c:3 },
  { t:'What is the official currency of Togo?',          o:['West African CFA franc','Belize dollar','Kuwaiti dinar','Tanzanian shilling'], c:0 },
  { t:'What is the official currency of Tunisia?',       o:['Colombian peso','Tunisian dinar','Bosnia convertible mark','Samoan tālā'], c:1 },
  { t:'What is the official currency of Uganda?',        o:['Trinidad and Tobago dollar','Brazilian real','Ugandan shilling','Belize dollar'], c:2 },
  { t:'What is the official currency of Zambia?',        o:['Djiboutian franc','Mauritian rupee','Burmese kyat','Zambian kwacha'], c:3 },
  { t:'What is the official currency of Zimbabwe?',      o:['Zimbabwe Gold','Kenyan shilling','Comorian franc','Sierra Leonean leone'], c:0 },
];

const CURRENCIES_EUROPE = [
  { t:'What is the official currency of Albania?',              o:['Israeli new shekel','Albanian lek','Uzbekistani soʻm','Qatari riyal'], c:1 },
  { t:'What is the official currency of Andorra?',              o:['Swazi lilangeni','Sudanese pound','Euro','Mauritian rupee'], c:2 },
  { t:'What is the official currency of Austria?',              o:['South African rand','Moldovan leu','Bolivian boliviano','Euro'], c:3 },
  { t:'What is the official currency of Belarus?',              o:['Belarusian ruble','Central African CFA franc','Indian rupee','Indonesian rupiah'], c:0 },
  { t:'What is the official currency of Belgium?',              o:['Lebanese pound','Euro','Brunei dollar','Eastern Caribbean dollar'], c:1 },
  { t:'What is the official currency of Bosnia and Herzegovina?', o:['Kazakhstani tenge','Fijian dollar','Bosnia convertible mark','Brunei dollar'], c:2 },
  { t:'What is the official currency of Bulgaria?',             o:['Eastern Caribbean dollar','Afghan afghani','Seychellois rupee','Euro'], c:3 },
  { t:'What is the official currency of Croatia?',              o:['Euro','Swazi lilangeni','Tajikistani somoni','Maldivian rufiyaa'], c:0 },
  { t:'What is the official currency of Cyprus?',               o:['Bahamian dollar','Euro','Japanese yen','Malaysian ringgit'], c:1 },
  { t:'What is the official currency of the Czech Republic?',   o:['Malawian kwacha','Swedish krona','Czech koruna','Brazilian real'], c:2 },
  { t:'What is the official currency of Denmark?',              o:['Japanese yen','Lebanese pound','Honduran lempira','Danish krone'], c:3 },
  { t:'What is the official currency of Estonia?',              o:['Euro','Somali shilling','Colombian peso','Zambian kwacha'], c:0 },
  { t:'What is the official currency of Finland?',              o:['Israeli new shekel','Euro','Djiboutian franc','Lesotho loti'], c:1 },
  { t:'What is the official currency of France?',               o:['Danish krone','Brazilian real','Euro','Bolivian boliviano'], c:2 },
  { t:'What is the official currency of Germany?',              o:['Eritrean nakfa','Moldovan leu','Malaysian ringgit','Euro'], c:3 },
  { t:'What is the official currency of Greece?',               o:['Euro','Sri Lankan rupee','Congolese franc','São Tomé dobra'], c:0 },
  { t:'What is the official currency of Hungary?',              o:['Mexican peso','Hungarian forint','Serbian dinar','Liberian dollar'], c:1 },
  { t:'What is the official currency of Iceland?',              o:['Ugandan shilling','Yemeni rial','Icelandic króna','Turkish lira'], c:2 },
  { t:'What is the official currency of Ireland?',              o:['Sri Lankan rupee','Brunei dollar','Bangladeshi taka','Euro'], c:3 },
  { t:'What is the official currency of Italy?',                o:['Euro','South Korean won','Namibian dollar','Kyrgyzstani som'], c:0 },
  { t:'What is the official currency of Latvia?',               o:['Australian dollar','Euro','Cambodian riel','Jamaican dollar'], c:1 },
  { t:'What is the official currency of Liechtenstein?',        o:['Armenian dram','Lebanese pound','Swiss franc','Bangladeshi taka'], c:2 },
  { t:'What is the official currency of Lithuania?',            o:['Fijian dollar','Tajikistani somoni','Uruguayan peso','Euro'], c:3 },
  { t:'What is the official currency of Luxembourg?',           o:['Euro','Sudanese pound','Malagasy ariary','Guatemalan quetzal'], c:0 },
  { t:'What is the official currency of Malta?',                o:['South Sudanese pound','Euro','Tunisian dinar','Cambodian riel'], c:1 },
  { t:'What is the official currency of Moldova?',              o:['Tajikistani somoni','Omani rial','Moldovan leu','Seychellois rupee'], c:2 },
  { t:'What is the official currency of Monaco?',               o:['Nicaraguan córdoba','Namibian dollar','Central African CFA franc','Euro'], c:3 },
  { t:'What is the official currency of Montenegro?',           o:['Euro','Egyptian pound','New Zealand dollar','Sierra Leonean leone'], c:0 },
  { t:'What is the official currency of the Netherlands?',      o:['Turkish lira','Euro','Malaysian ringgit','Saudi riyal'], c:1 },
  { t:'What is the official currency of North Macedonia?',      o:['Zimbabwe Gold','Bahraini dinar','Denar','Swedish krona'], c:2 },
  { t:'What is the official currency of Norway?',               o:['Burundian franc','Mongolian tögrög','Kuwaiti dinar','Norwegian krone'], c:3 },
  { t:'What is the official currency of Poland?',               o:['Polish złoty','Mozambican metical','Colombian peso','Serbian dinar'], c:0 },
  { t:'What is the official currency of Portugal?',             o:['United States dollar','Euro','Afghan afghani','Yemeni rial'], c:1 },
  { t:'What is the official currency of Romania?',              o:['Syrian pound','Sierra Leonean leone','Romanian leu','Belize dollar'], c:2 },
  { t:'What is the official currency of Russia?',               o:['Guinean franc','Uruguayan peso','Panamanian balboa','Russian ruble'], c:3 },
  { t:'What is the official currency of San Marino?',           o:['Euro','Turkmenistan manat','Sudanese pound','Belize dollar'], c:0 },
  { t:'What is the official currency of Serbia?',               o:['Hungarian forint','Serbian dinar','Lebanese pound','Zimbabwe Gold'], c:1 },
  { t:'What is the official currency of Slovakia?',             o:['Cuban peso','Malaysian ringgit','Euro','Sri Lankan rupee'], c:2 },
  { t:'What is the official currency of Slovenia?',             o:['Trinidad and Tobago dollar','Congolese franc','Azerbaijani manat','Euro'], c:3 },
  { t:'What is the official currency of Spain?',                o:['Euro','Kazakhstani tenge','Eastern Caribbean dollar','Mongolian tögrög'], c:0 },
  { t:'What is the official currency of Sweden?',               o:['Angolan kwanza','Swedish krona','Serbian dinar','Cambodian riel'], c:1 },
  { t:'What is the official currency of Switzerland?',          o:['Iraqi dinar','Colombian peso','Swiss franc','Syrian pound'], c:2 },
  { t:'What is the official currency of Ukraine?',              o:['Comorian franc','Dominican peso','Turkish lira','Ukrainian hryvnia'], c:3 },
  { t:'What is the official currency of the United Kingdom?',   o:['British pound','Maldivian rufiyaa','UAE dirham','Liberian dollar'], c:0 },
  { t:'What is the official currency of Vatican City (Holy See)?', o:['Singapore dollar','Euro','Tongan paʻanga','Tajikistani somoni'], c:1 },
];

const CURRENCIES_AMERICAS = [
  { t:'What is the official currency of Antigua and Barbuda?',  o:['Kenyan shilling','Swedish krona','Eastern Caribbean dollar','Denar'], c:2 },
  { t:'What is the official currency of Argentina?',            o:['Romanian leu','Guyanese dollar','UAE dirham','Argentine peso'], c:3 },
  { t:'What is the official currency of the Bahamas?',          o:['Bahamian dollar','Dalasi','Brazilian real','Libyan dinar'], c:0 },
  { t:'What is the official currency of Barbados?',             o:['Singapore dollar','Barbadian dollar','North Korean won','Ukrainian hryvnia'], c:1 },
  { t:'What is the official currency of Belize?',               o:['Lesotho loti','Afghan afghani','Belize dollar','Malawian kwacha'], c:2 },
  { t:'What is the official currency of Bolivia?',              o:['Mauritian rupee','Tunisian dinar','Dominican peso','Bolivian boliviano'], c:3 },
  { t:'What is the official currency of Brazil?',               o:['Brazilian real','Surinamese dollar','West African CFA franc','Tongan paʻanga'], c:0 },
  { t:'What is the official currency of Canada?',               o:['Norwegian krone','Canadian dollar','Nicaraguan córdoba','Zambian kwacha'], c:1 },
  { t:'What is the official currency of Chile?',                o:['Polish złoty','Swedish krona','Chilean peso','Namibian dollar'], c:2 },
  { t:'What is the official currency of Colombia?',             o:['Guyanese dollar','Kazakhstani tenge','Romanian leu','Colombian peso'], c:3 },
  { t:'What is the official currency of Costa Rica?',           o:['Costa Rican colón','Japanese yen','Sierra Leonean leone','Barbadian dollar'], c:0 },
  { t:'What is the official currency of Cuba?',                 o:['Mozambican metical','Cuban peso','Tanzanian shilling','Qatari riyal'], c:1 },
  { t:'What is the official currency of Dominica?',             o:['Romanian leu','Djiboutian franc','Eastern Caribbean dollar','Turkish lira'], c:2 },
  { t:'What is the official currency of the Dominican Republic?', o:['Bahraini dinar','Costa Rican colón','Ugandan shilling','Dominican peso'], c:3 },
  { t:'What is the official currency of Ecuador?',              o:['United States dollar','Nepalese rupee','Cape Verdean escudo','South Sudanese pound'], c:0 },
  { t:'What is the official currency of El Salvador?',          o:['Cape Verdean escudo','United States dollar','Vanuatu vatu','Swazi lilangeni'], c:1 },
  { t:'What is the official currency of Grenada?',              o:['Angolan kwanza','Danish krone','Eastern Caribbean dollar','Seychellois rupee'], c:2 },
  { t:'What is the official currency of Guatemala?',            o:['Dominican peso','British pound','Tajikistani somoni','Guatemalan quetzal'], c:3 },
  { t:'What is the official currency of Guyana?',               o:['Guyanese dollar','Lebanese pound','Nigerian naira','Samoan tālā'], c:0 },
  { t:'What is the official currency of Haiti?',                o:['Brunei dollar','Haitian gourde','New Zealand dollar','Vietnamese đồng'], c:1 },
  { t:'What is the official currency of Honduras?',             o:['Qatari riyal','Mozambican metical','Honduran lempira','Trinidad and Tobago dollar'], c:2 },
  { t:'What is the official currency of Jamaica?',              o:['Yemeni rial','Bahraini dinar','Botswana pula','Jamaican dollar'], c:3 },
  { t:'What is the official currency of Mexico?',               o:['Mexican peso','Japanese yen','Malawian kwacha','Israeli new shekel'], c:0 },
  { t:'What is the official currency of Nicaragua?',            o:['Cambodian riel','Nicaraguan córdoba','South Sudanese pound','Cape Verdean escudo'], c:1 },
  { t:'What is the official currency of Panama?',               o:['Cape Verdean escudo','Sudanese pound','Panamanian balboa','Eritrean nakfa'], c:2 },
  { t:'What is the official currency of Paraguay?',             o:['Mauritanian ouguiya','Azerbaijani manat','Barbadian dollar','Paraguayan guaraní'], c:3 },
  { t:'What is the official currency of Peru?',                 o:['Peruvian sol','Namibian dollar','Bhutanese ngultrum','Maldivian rufiyaa'], c:0 },
  { t:'What is the official currency of Saint Kitts and Nevis?', o:['Panamanian balboa','Eastern Caribbean dollar','Philippine peso','South Korean won'], c:1 },
  { t:'What is the official currency of Saint Lucia?',          o:['Denar','Kenyan shilling','Eastern Caribbean dollar','Venezuelan bolívar'], c:2 },
  { t:'What is the official currency of Saint Vincent and the Grenadines?', o:['Sierra Leonean leone','Guatemalan quetzal','Euro','Eastern Caribbean dollar'], c:3 },
  { t:'What is the official currency of Suriname?',             o:['Surinamese dollar','Euro','Brunei dollar','Polish złoty'], c:0 },
  { t:'What is the official currency of Trinidad and Tobago?',  o:['Jordanian dinar','Trinidad and Tobago dollar','Turkmenistan manat','Danish krone'], c:1 },
  { t:'What is the official currency of the United States?',    o:['Jamaican dollar','Swiss franc','United States dollar','Kyrgyzstani som'], c:2 },
  { t:'What is the official currency of Uruguay?',              o:['Swedish krona','Kyrgyzstani som','Algerian dinar','Uruguayan peso'], c:3 },
  { t:'What is the official currency of Venezuela?',            o:['Venezuelan bolívar soberano','Syrian pound','Malawian kwacha','Zambian kwacha'], c:0 },
];

const CURRENCIES_OCEANIA = [
  { t:'What is the official currency of Australia?',           o:['Egyptian pound','Australian dollar','British pound','Sudanese pound'], c:1 },
  { t:'What is the official currency of Fiji?',                o:['Norwegian krone','Mauritian rupee','Fijian dollar','Somali shilling'], c:2 },
  { t:'What is the official currency of Kiribati?',            o:['Kyrgyzstani som','Swedish krona','Mexican peso','Australian dollar'], c:3 },
  { t:'What is the official currency of the Marshall Islands?', o:['United States dollar','Haitian gourde','Qatari riyal','Thai baht'], c:0 },
  { t:'What is the official currency of Micronesia?',          o:['Chilean peso','United States dollar','Japanese yen','Polish złoty'], c:1 },
  { t:'What is the official currency of Nauru?',               o:['Panamanian balboa','Mauritanian ouguiya','Australian dollar','Armenian dram'], c:2 },
  { t:'What is the official currency of New Zealand?',         o:['Samoan tālā','Liberian dollar','Algerian dinar','New Zealand dollar'], c:3 },
  { t:'What is the official currency of Palau?',               o:['United States dollar','Belarusian ruble','Turkish lira','Malawian kwacha'], c:0 },
  { t:'What is the official currency of Papua New Guinea?',    o:['Israeli new shekel','Papua New Guinean kina','Omani rial','Iranian rial'], c:1 },
  { t:'What is the official currency of Samoa?',               o:['Guinean franc','Kuwaiti dinar','Samoan tālā','Dalasi'], c:2 },
  { t:'What is the official currency of the Solomon Islands?', o:['Canadian dollar','Bangladeshi taka','Moldovan leu','Solomon Islands dollar'], c:3 },
  { t:'What is the official currency of Tonga?',               o:['Tongan paʻanga','South Sudanese pound','Bahamian dollar','Papua New Guinean kina'], c:0 },
  { t:'What is the official currency of Tuvalu?',              o:['Czech koruna','Australian dollar','Canadian dollar','Mauritanian ouguiya'], c:1 },
  { t:'What is the official currency of Vanuatu?',             o:['Namibian dollar','Sierra Leonean leone','Vanuatu vatu','Euro'], c:2 },
];

// ─── WORLD LEADERS ───────────────────────────────────────────────────────────

const WORLD_LEADERS = [
  { t:'Who is the current Prime Minister of Pakistan?',           o:['Shehbaz Sharif','Friedrich Merz','Keir Starmer','Lee Jae Myung'],          c:0 },
  { t:'Who is the current Prime Minister of India?',              o:['Cyril Ramaphosa','Narendra Modi','Sheikh Tamim bin Hamad Al Thani','Masoud Pezeshkian'], c:1 },
  { t:'Who is the current President of China?',                   o:['Abdel Fattah el-Sisi','King Salman bin Abdulaziz Al Saud','Xi Jinping','Kim Jong-un'], c:2 },
  { t:'Who is the current President of the United States?',       o:['Emmanuel Macron','King Salman bin Abdulaziz Al Saud','Kim Jong-un','Donald Trump'], c:3 },
  { t:'Who is the current President of Russia?',                  o:['Vladimir Putin','Balendra Shah','Lee Jae Myung','Mohamed bin Zayed Al Nahyan'], c:0 },
  { t:'Who is the current Prime Minister of the United Kingdom?', o:['Prabowo Subianto','Keir Starmer','Benjamin Netanyahu','Recep Tayyip Erdogan'], c:1 },
  { t:'Who is the current President of France?',                  o:['Lee Jae Myung','Donald Trump','Emmanuel Macron','Anura Kumara Dissanayake'], c:2 },
  { t:'Who is the current Chancellor of Germany?',                o:['Xi Jinping','Vladimir Putin','Anwar Ibrahim','Friedrich Merz'], c:3 },
  { t:'Who is the current Prime Minister of Japan?',              o:['Sanae Takaichi','Friedrich Merz','Benjamin Netanyahu','Anthony Albanese'], c:0 },
  { t:'Who is the current King of Saudi Arabia?',                 o:['Prabowo Subianto','King Salman bin Abdulaziz Al Saud','Anthony Albanese','Hibatullah Akhundzada'], c:1 },
  { t:'Who is the current President of the United Arab Emirates?', o:['Benjamin Netanyahu','Lee Jae Myung','Mohamed bin Zayed Al Nahyan','Cyril Ramaphosa'], c:2 },
  { t:'Who is the current President of Turkey?',                  o:['Masoud Pezeshkian','Xi Jinping','Lee Jae Myung','Recep Tayyip Erdogan'], c:3 },
  { t:'Who is the current President of Iran?',                    o:['Masoud Pezeshkian','Hibatullah Akhundzada','Shehbaz Sharif','Sanae Takaichi'], c:0 },
  { t:'Who is the current Prime Minister of Israel?',             o:['Anwar Ibrahim','Benjamin Netanyahu','Cyril Ramaphosa','Recep Tayyip Erdogan'], c:1 },
  { t:'Who is the current President of South Korea?',             o:['Prabowo Subianto','Xi Jinping','Lee Jae Myung','Kim Jong-un'], c:2 },
  { t:'Who is the current President of Indonesia?',               o:['Anthony Albanese','Anwar Ibrahim','Sanae Takaichi','Prabowo Subianto'], c:3 },
  { t:'Who is the current Prime Minister of Australia?',          o:['Anthony Albanese','Friedrich Merz','Keir Starmer','Narendra Modi'], c:0 },
  { t:'Who is the current Prime Minister of Malaysia?',           o:['Lee Jae Myung','Anwar Ibrahim','Prabowo Subianto','Cyril Ramaphosa'], c:1 },
  { t:'Who is the current President of Egypt?',                   o:['King Salman bin Abdulaziz Al Saud','Masoud Pezeshkian','Abdel Fattah el-Sisi','Vladimir Putin'], c:2 },
  { t:'Who is the current President of South Africa?',            o:['Anura Kumara Dissanayake','Hibatullah Akhundzada','Prabowo Subianto','Cyril Ramaphosa'], c:3 },
  { t:'Who is the current President of Brazil?',                  o:['Luiz Inácio Lula da Silva','Emmanuel Macron','Donald Trump','Friedrich Merz'], c:0 },
  { t:'Who is the current Prime Minister of Canada?',             o:['Keir Starmer','Mark Carney','Anthony Albanese','Narendra Modi'], c:1 },
  { t:'Who is the current Supreme Leader of Afghanistan?',        o:['Masoud Pezeshkian','Kim Jong-un','Hibatullah Akhundzada','Recep Tayyip Erdogan'], c:2 },
  { t:'Who is the current President of Sri Lanka?',               o:['Narendra Modi','Prabowo Subianto','Lee Jae Myung','Anura Kumara Dissanayake'], c:3 },
  { t:'Who is the current Emir of Qatar?',                        o:['Sheikh Tamim bin Hamad Al Thani','King Salman bin Abdulaziz Al Saud','Mohamed bin Zayed Al Nahyan','Masoud Pezeshkian'], c:0 },
  { t:'Who is the current Leader of North Korea?',                o:['Xi Jinping','Kim Jong-un','Recep Tayyip Erdogan','Vladimir Putin'], c:1 },
  { t:'Who is the current Chief Adviser of Bangladesh?',          o:['Keir Starmer','Shehbaz Sharif','Muhammad Yunus','Narendra Modi'], c:2 },
  { t:'Who is the current President of Pakistan?',                o:['Shehbaz Sharif','Narendra Modi','Vladimir Putin','Asif Ali Zardari'], c:3 },
  { t:'Who is the current King of Jordan?',                       o:['King Abdullah II','King Salman','Sheikh Tamim','Mohamed bin Zayed'], c:0 },
  { t:'Who is the current President of Afghanistan (internationally recognised)?', o:['Hibatullah Akhundzada','Ashraf Ghani','Hamid Karzai','Ahmad Massoud'], c:0 },
];

// ─── SEED FUNCTION ───────────────────────────────────────────────────────────

async function seedWorldInfo() {
  const client = new Client({ connectionString });
  await client.connect();
  console.log('✅ Connected to Neon DB for World Info MCQs...');

  try {
    await client.query('BEGIN');

    const batches = [
      { subject: 'World Capitals - Asia',       data: CAPITALS_ASIA,       prefix: 'wc-asia' },
      { subject: 'World Capitals - Africa',     data: CAPITALS_AFRICA,     prefix: 'wc-afr' },
      { subject: 'World Capitals - Europe',     data: CAPITALS_EUROPE,     prefix: 'wc-eur' },
      { subject: 'World Capitals - Americas',   data: CAPITALS_AMERICAS,   prefix: 'wc-ame' },
      { subject: 'World Capitals - Oceania',    data: CAPITALS_OCEANIA,    prefix: 'wc-oce' },
      { subject: 'World Currencies - Asia',     data: CURRENCIES_ASIA,     prefix: 'wcu-asia' },
      { subject: 'World Currencies - Africa',   data: CURRENCIES_AFRICA,   prefix: 'wcu-afr' },
      { subject: 'World Currencies - Europe',   data: CURRENCIES_EUROPE,   prefix: 'wcu-eur' },
      { subject: 'World Currencies - Americas', data: CURRENCIES_AMERICAS, prefix: 'wcu-ame' },
      { subject: 'World Currencies - Oceania',  data: CURRENCIES_OCEANIA,  prefix: 'wcu-oce' },
      { subject: 'World Leaders',               data: WORLD_LEADERS,       prefix: 'wl' },
    ];

    let totalInserted = 0;
    for (const batch of batches) {
      for (let i = 0; i < batch.data.length; i++) {
        const q = batch.data[i];
        const qId = `${batch.prefix}-${i + 1}`;
        await client.query(`
          INSERT INTO "Question" (id, "textEn", "textUr", "optionsEn", "optionsUr", "correctIndex", subject, difficulty, "createdAt", "updatedAt")
          VALUES ($1, $2, $3, $4, $5, $6, $7, 'medium', NOW(), NOW())
          ON CONFLICT (id) DO UPDATE SET "textEn"=EXCLUDED."textEn", "optionsEn"=EXCLUDED."optionsEn", "correctIndex"=EXCLUDED."correctIndex", subject=EXCLUDED.subject
        `, [qId, q.t, q.t, q.o, q.o, q.c, batch.subject]);
        totalInserted++;
      }
      console.log(`  ✅ ${batch.subject}: ${batch.data.length} questions inserted`);
    }

    await client.query('COMMIT');
    console.log(`\n🎉 SUCCESS! Total ${totalInserted} World Info MCQs seeded into Neon DB!`);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌ Error:', err.message);
  } finally {
    await client.end();
  }
}

seedWorldInfo().catch(console.error);
