const { Client } = require('pg');

const connectionString = 'postgresql://neondb_owner:npg_wkeHO3sTxiE6@ep-rough-rice-ax0e6jfa-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require';

const pakStudiesQuestions = [
  { t: "History Is The Study Of ______, Particularly People, Places And Historical Events.", o: ["Present", "Past", "Future", "Culture"], c: 1 },
  { t: "We Can Study History By Using Two Types Of Sources Called ______ And ______.", o: ["Primary, Secondary", "Old, New", "Written, Oral", "Formal, Informal"], c: 0 },
  { t: "History Must Be Based On ______ And ______.", o: ["Opinions, Beliefs", "Evidence, Logical Thought", "Guesses, Assumptions", "Myths, Legends"], c: 1 },
  { t: "Two Important Theories About The Origin Of Human Life Are ______ And ______.", o: ["Creation, Evolution", "Science, Religion", "Ancient, Modern", "Eastern, Western"], c: 0 },
  { t: "Bipedalism Means The Ability To ______.", o: ["Walk On Two Legs", "Climb Trees", "Swim", "Fly"], c: 0 },
  { t: "The Early Humans Went From Place To Place In Search Of ______.", o: ["Shelter", "Clothing", "Food", "Water"], c: 2 },
  { t: "Scientists Believe That Humans Evolved From An Ape-Like Ancestor About ______ Million Years Ago.", o: ["2", "4", "6", "10"], c: 2 },
  { t: "Modern Human Beings Are Known As ______.", o: ["Homo Habilis", "Homo Erectus", "Neanderthal", "Homo Sapiens"], c: 3 },
  { t: "Which Theory States That God Created Human Beings?", o: ["Theory Of Evolution", "Theory Of Creation", "Theory Of Relativity", "Theory Of Gravity"], c: 1 },
  { t: "Charles Darwin Published His Book \"The Origin Of Species\" In Which Year?", o: ["1849", "1859", "1869", "1879"], c: 1 },
  { t: "Earth Is About ______ Billion Years Old.", o: ["2.5", "3.5", "4.5", "5.5"], c: 2 },
  { t: "The Study Of Humans, Past And Present Is Called ______.", o: ["Archaeology", "Anthropology", "Sociology", "Psychology"], c: 1 },
  { t: "The ______ Society Emerged Around 10,000 Years Ago.", o: ["Industrial", "Agricultural", "Pastoral", "Post-Industrial"], c: 1 },
  { t: "The Change From An Agricultural To An Industrial Society Was Brought About By The ______.", o: ["Green Revolution", "Industrial Revolution", "French Revolution", "Digital Revolution"], c: 1 },
  { t: "An Agricultural Society Is One In Which Crops Are ______ And Animals Are ______.", o: ["Planted, Hunted", "Grown, Domesticated", "Harvested, Captured", "Bought, Sold"], c: 1 },
  { t: "Today's Society Would Be Called A ______.", o: ["Agricultural Society", "Industrial Society", "Post-Industrial Society", "Hunting-Gathering Society"], c: 2 },
  { t: "Culture Is The ______ Of A Group Of People.", o: ["Genetic Makeup", "Way Of Life", "Economic System", "Political System"], c: 1 },
  { t: "A Set Of Beliefs About Life And The World Is Called A ______.", o: ["Culture", "Civilization", "World-View", "Tradition"], c: 2 },
  { t: "When Most Members Of A Society Share A Set Of Beliefs About Life And The World They Have A ______.", o: ["Personal World-View", "Societal World-View", "Cultural Identity", "National Identity"], c: 1 },
  { t: "A Society That Has Reached An Advanced State Of Social Development And Organization Is Called A ______.", o: ["Community", "Nation", "Civilization", "State"], c: 2 },
  { t: "The First Civilization Began To Appear Around ______ BCE.", o: ["2500", "3500", "4500", "5500"], c: 1 },
  { t: "All Early Civilizations Started Along The Banks Of ______.", o: ["Oceans", "Rivers", "Mountains", "Deserts"], c: 1 },
  { t: "The Indus Valley Civilization Grew Along The Bank Of The ______.", o: ["River Ganges", "River Indus", "River Brahmaputra", "River Nile"], c: 1 },
  { t: "The Civilization Existed Between ______ And ______ BCE.", o: ["2500, 1500", "3300, 1300", "4000, 2000", "5000, 3000"], c: 1 },
  { t: "The Two Main Cities Of The Indus Valley Civilization Are ______ And ______.", o: ["Moen-Jo-Daro, Lothal", "Harappa, Moen-Jo-Daro", "Harappa, Dholavira", "Moen-Jo-Daro, Kalibangan"], c: 1 },
  { t: "Our Knowledge Of The People And Their Way Of Life Comes From Studying The ______ That Have Been Unearthed.", o: ["Books", "Inscriptions", "Artifacts", "Manuscripts"], c: 2 },
  { t: "Children's Toys Include ______ And ______.", o: ["Carts, Animal Figures", "Balls, Dolls", "Puzzles, Board Games", "Ropes, Kites"], c: 0 },
  { t: "The Indus Valley Civilization Extended Over An Area Of ______ Million Sq Km.", o: ["0.75", "1.00", "1.25", "1.50"], c: 2 },
  { t: "At Its Peak, The Indus Valley Civilization Had A Population Of More Than ______ Million People.", o: ["3", "4", "5", "6"], c: 2 },
  { t: "The \"Priest-King\" Statue Was Found At Which City?", o: ["Harappa", "Moen-Jo-Daro", "Lothal", "Dholavira"], c: 1 },
  { t: "All Indus Valley Bricks Were The Same Ratio Of ______.", o: ["1:2:3", "1:2:4", "1:3:5", "2:3:4"], c: 1 },
  { t: "The People Of The Indus Valley Civilization Were Good In ______ And ______.", o: ["Farming, Trade", "Art, Architecture", "Writing, Reading", "Fishing, Hunting"], c: 1 },
  { t: "Houses And Other Buildings Were Made Of ______.", o: ["Stone", "Wood", "Baked Bricks", "Mud"], c: 2 },
  { t: "Three Forms Of Art In The Indus Valley Civilization Were ______, ______ And ______.", o: ["Sculpture, Pottery, Jewellery", "Painting, Dance, Music", "Writing, Carving, Weaving", "Metalwork, Glass, Woodwork"], c: 0 },
  { t: "We Know That The People Engaged In Some Form Of Dancing Because A Statuette Of A ______ Was Found.", o: ["Boy", "Priest", "Dancing Girl", "King"], c: 2 },
  { t: "Seals With Writing On Them Were Used For Trading. This Shows That The Traders Could ______.", o: ["Read And Write", "Trade Goods", "Travel Far", "Speak Many Languages"], c: 0 },
  { t: "The Great Bath Is Located At Which City?", o: ["Harappa", "Moen-Jo-Daro", "Lothal", "Dholavira"], c: 1 },
  { t: "How Many Different Characters Have Been Identified In The Indus Valley Writing System?", o: ["200", "300", "400", "500"], c: 2 },
  { t: "Buttons Made From Seashell Were Used In The Indus Valley Civilization By ______ BCE.", o: ["1000", "1500", "2000", "2500"], c: 3 },
  { t: "A Harp-Like Instrument Depicted On An Indus Seal Indicates The Use Of ______.", o: ["Percussion Instruments", "Wind Instruments", "Stringed Instruments", "Brass Instruments"], c: 2 },
  { t: "A System Of Measurement Was Developed To Measure ______, ______ And ______.", o: ["Length, Mass, Time", "Weight, Height, Volume", "Distance, Speed, Temperature", "Area, Capacity, Density"], c: 0 },
  { t: "Most Tools Were Made Of ______.", o: ["Bronze", "Copper", "Stone", "Iron"], c: 2 },
  { t: "New Techniques Of Metallurgy Resulted In The Development Of ______, ______ And ______.", o: ["Copper, Bronze, Lead", "Gold, Silver, Platinum", "Iron, Steel, Tin", "Aluminum, Zinc, Nickel"], c: 0 },
  { t: "The Economy Of The Indus Valley Civilization Depended On ______.", o: ["Farming", "Trade", "Fishing", "Mining"], c: 1 },
  { t: "Trade With Other Places Was Facilitated By The Development Of ______ And ______.", o: ["Roads, Bridges", "Bullock Carts, Boats", "Horses, Camels", "Ships, Trains"], c: 1 },
  { t: "Weights Were Based On Units Of ______ Grams.", o: ["25", "28", "30", "35"], c: 1 },
  { t: "The Smallest Cube Used As Weight Weighed Less Than ______ Gram.", o: ["1", "2", "3", "4"], c: 0 },
  { t: "The Largest Cube Used As Weight Weighed Over ______ Kilograms.", o: ["5", "8", "11", "15"], c: 2 },
  { t: "A Ruler Made From Ivory Found At Lothal Was Divided Into Units Corresponding To ______ Mm.", o: ["25.5", "30.5", "33.5", "35.5"], c: 2 },
  { t: "The Indus Valley Civilization Came To An End Around ______ BCE.", o: ["1000", "1300", "1500", "2000"], c: 1 },
  { t: "Historians Have Not Been Able To Find The Cause That Resulted In The Civilization Coming To An ______.", o: ["Beginning", "End", "Start", "Peak"], c: 1 },
  { t: "Around ______ BCE Major Climatic Changes Occurred In The Indus Valley.", o: ["1000", "1500", "2000", "2500"], c: 2 },
  { t: "Three Reasons Why The Indus Valley Civilization Is Important For Us Are ______, ______ And ______.", o: ["Art, Trade, Farming", "Cleanliness, Town Planning, Peace", "Writing, Religion, Science", "Architecture, Tools, Music"], c: 1 },
  { t: "The Ochre Colored Pottery Of The Indus Valley Civilization Is Still Made In The Whole Region ______.", o: ["Today", "Yesterday", "Tomorrow", "Never"], c: 0 },
  { t: "The System By Which A Community Is Governed Is Called ______.", o: ["State", "Government", "Parliament", "Constitution"], c: 1 },
  { t: "The Government Makes ______ To Rule The Country.", o: ["Laws", "Money", "Products", "Services"], c: 0 },
  { t: "Pakistan Has A ______ And ______ Form Of Government.", o: ["Presidential, Democratic", "Federal, Parliamentary", "Unitary, Presidential", "Federal, Presidential"], c: 1 },
  { t: "In A Federal System Of Government, Powers Are Shared Between The ______ And The ______.", o: ["Centre, Provinces", "Provinces, Districts", "Federal, Local", "Federal, Provincial"], c: 3 },
  { t: "In A Parliamentary Form Of Government, The Legislative And Executive Branches Are Not ______.", o: ["Separated", "Combined", "Divided", "Distinct"], c: 0 },
  { t: "Democracy Means Rule By The ______.", o: ["People", "King", "Military", "Elites"], c: 0 },
  { t: "The 1973 Constitution Of Pakistan Lists The ______ Rights Of Citizens.", o: ["Political", "Economic", "Fundamental", "Social"], c: 2 },
  { t: "FATA Stands For ______.", o: ["Federally Administered Tribal Areas", "Federal Administrative Tribal Areas", "Federally Associated Territorial Areas", "Federal Allied Tribal Areas"], c: 0 },
  { t: "Three Branches Of Government Are ______, ______ And ______.", o: ["Legislative, Executive, Judicial", "Federal, Provincial, Local", "Parliament, Senate, Court", "Upper, Lower, Middle"], c: 0 },
  { t: "The Legislative Branch Or Parliament Consists Of Two Houses: ______ And ______.", o: ["National Assembly, Senate", "National Assembly, Provincial Assembly", "Senate, Provincial Assembly", "Upper House, Lower House"], c: 0 },
  { t: "The Head Of Government In Pakistan Is The ______.", o: ["President", "Prime Minister", "Chief Justice", "Speaker"], c: 1 },
  { t: "The Prime Minister Appoints The Cabinet From The Members Of The ______.", o: ["Senate", "National Assembly", "Provincial Assembly", "Supreme Court"], c: 1 },
  { t: "The Highest Court Of Pakistan Is The ______.", o: ["High Court", "Federal Shariat Court", "Supreme Court", "District Court"], c: 2 },
  { t: "The Total Membership Of The National Assembly Is ______.", o: ["272", "342", "442", "542"], c: 1 },
  { t: "The Senate Has ______ Members.", o: ["104", "114", "124", "134"], c: 0 },
  { t: "The Term Of The Senate Members Is ______ Years.", o: ["4", "5", "6", "7"], c: 2 },
  { t: "One-Half Of The Senate Members Retire After Every ______ Years.", o: ["2", "3", "4", "5"], c: 1 },
  { t: "The Minimum Age To Become A Member Of The Senate Is ______ Years.", o: ["25", "28", "30", "35"], c: 2 },
  { t: "The President Of Pakistan Is The Supreme Commander Of The ______.", o: ["Armed Forces", "Civil Service", "Judiciary", "Parliament"], c: 0 },
  { t: "The Chief Justice Of The Supreme Court May Remain In Office Until The Age Of ______.", o: ["60", "62", "65", "70"], c: 2 },
  { t: "According To Sindh Local Govt Act 2013, There Are ______ Tiers Of Local Government.", o: ["2", "3", "4", "5"], c: 1 },
  { t: "The Three Tiers Of Local Government Are ______, ______ And ______.", o: ["District, Taluka, Union", "City, Town, Village", "Provincial, District, Taluka", "Federal, Provincial, Local"], c: 0 },
  { t: "In Metropolitan Cities, The Chairman Is Called ______.", o: ["Commissioner", "Mayor", "Deputy Commissioner", "Administrator"], c: 1 },
  { t: "Councilors Are Elected On ______ Basis.", o: ["Party", "Non-Party", "Religious", "Ethnic"], c: 1 },
  { t: "Councilors Serve A Term Of ______ Years.", o: ["2", "3", "4", "5"], c: 2 },
  { t: "In Pakistan, General Elections Are Held After Every ______ Years.", o: ["3", "4", "5", "6"], c: 2 },
  { t: "The Age Of The Voter In Pakistan Is ______ Years.", o: ["16", "17", "18", "20"], c: 2 },
  { t: "The Minimum Age Of The Representatives In Pakistan Is ______ Years.", o: ["18", "21", "25", "30"], c: 2 },
  { t: "The Body Which Is Responsible For Conducting The Elections In The Country Is Called ______.", o: ["Election Commission Of Pakistan", "Supreme Court", "Parliament", "National Assembly"], c: 0 },
  { t: "The Chief Election Commissioner Has To Be A Serving Or A Former Judge Of The ______.", o: ["High Court", "Supreme Court", "District Court", "Federal Shariat Court"], c: 1 },
  { t: "\"Government Of The People, By The People, For The People\" Is A Quote By ______.", o: ["Abraham Lincoln", "George Washington", "Winston Churchill", "Muhammad Ali Jinnah"], c: 0 },
  { t: "ECP Stands For ______.", o: ["Election Commission Of Pakistan", "Electoral Committee Of Pakistan", "Election Council Of Pakistan", "Electoral Commission Of Pakistan"], c: 0 },
  { t: "PEMRA Was Established In ______.", o: ["2000", "2001", "2002", "2003"], c: 2 },
  { t: "The Pakistan Press, Newspapers, News Agencies And Books Registration Ordinance (PNNABRO) Regulates The ______ Media.", o: ["Electronic", "Print", "Social", "Digital"], c: 1 },
  { t: "The Different Channels Used To Communicate With Others Are Called ______.", o: ["Media", "Technology", "Communication", "Information"], c: 0 },
  { t: "The Use Of Electronic Communication Channels To Communicate With Others Is Called ______.", o: ["Print Media", "Electronic Media", "Social Media", "Digital Media"], c: 1 },
  { t: "The Main Source Of Income For Media Houses Comes From ______.", o: ["Subscriptions", "Government Funding", "Advertising", "Donations"], c: 2 },
  { t: "The Message Encoded Via A Machine Readable Format Is Called ______.", o: ["Print Media", "Electronic Media", "Digital Media", "Social Media"], c: 2 },
  { t: "The Communication Delivered In A Paper Format Is Called ______.", o: ["Print Media", "Electronic Media", "Digital Media", "Social Media"], c: 0 },
  { t: "The Interaction Among People By Use Of Internet And Telephone Technologies Is Called ______.", o: ["Print Media", "Electronic Media", "Digital Media", "Social Media"], c: 3 },
  { t: "Examples Of Print Media Are ______, ______ And ______.", o: ["Newspapers, Books, Magazines", "Radio, TV, Internet", "Websites, Blogs, Emails", "Social Media, Apps, Games"], c: 0 },
  { t: "Skype, Twitter, Linkedin, Google And Youtube Are Examples Of ______ Media.", o: ["Print", "Electronic", "Digital", "Social"], c: 3 },
  { t: "The Media Helps To Promote And Protect The Rights To ______ And ______.", o: ["Speech, Expression", "Education, Health", "Property, Security", "Freedom Of Speech, Freedom Of Information"], c: 3 },
  { t: "When The Media Reports On The Actions Of Public Officials, It Is Playing The Role Of A ______.", o: ["Watchdog", "Teacher", "Entertainer", "Advertiser"], c: 0 },
  { t: "Freedom Of Information Helps Citizens To Make Informed Choices When Choosing ______ For Public Officials In The Upcoming Elections.", o: ["To Vote", "To Work", "To Stand", "To Apply"], c: 0 },
  { t: "The Media Must Be ______ And ______ If It Is To Play The Role Of Watchdog.", o: ["Free, Independent", "Strong, Powerful", "Popular, Wealthy", "Large, Influential"], c: 0 },
  { t: "Article 19 Of The Constitution Guarantees The Right To ______.", o: ["Education", "Health", "Freedom Of Speech", "Property"], c: 2 },
  { t: "Article 19(A) Guarantees The Right To ______.", o: ["Education", "Health", "Information", "Property"], c: 2 },
  { t: "PNNABRO Was Established In ______.", o: ["2000", "2001", "2002", "2003"], c: 2 },
  { t: "The Media Often Seek Not Only To Inform, But Also To ______ Us.", o: ["Educate", "Entertain", "Influence", "Inspire"], c: 2 },
  { t: "A Fact Can Be ______.", o: ["Proven", "Believed", "Imagined", "Guessed"], c: 0 },
  { t: "The Tendency To Favour One Person, Group Or View-Point Over Another Is Called ______.", o: ["Bias", "Propaganda", "Stereotyping", "Prejudice"], c: 0 },
  { t: "The Technique Of Using Information To Arouse Feelings Is Called ______.", o: ["Name-Calling", "Bandwagon", "Appeal To Emotion", "Transfer"], c: 2 },
  { t: "When All Women Or All Men Are Said To Behave In A Certain Way, This Is An Example Of ______.", o: ["Bias", "Propaganda", "Stereotyping", "Prejudice"], c: 2 },
  { t: "A Stereotype Is A ______ That Is Too Simple, Usually Exaggerated And Often Offensive.", o: ["Generalization", "Fact", "Opinion", "Belief"], c: 0 },
  { t: "Propaganda Is The Systematic Effort To Spread Opinions Or Beliefs, Often By ______.", o: ["Evidence And Proof", "Distortion And Deception", "Logic And Reason", "Honesty And Truth"], c: 1 },
  { t: "The Technique That Uses A Famous Person To Say That An Idea Is Good Is Called ______.", o: ["Testimonial", "Plain Folks", "Glittering Generalities", "Transfer"], c: 0 },
  { t: "The Technique That Claims \"Everyone\" Has One Or \"Everyone\" Is Doing It Is Called ______.", o: ["Name-Calling", "Bandwagon", "Card Stacking", "Transfer"], c: 1 },
  { t: "Quaid-I-Azam Mohammad Ali Jinnah Died On September 11, 1948 Is An Example Of A ______.", o: ["Opinion", "Fact", "Belief", "Judgment"], c: 1 },
  { t: "\"My Mother Is The Best Cook In The World\" Is An Example Of An ______.", o: ["Fact", "Opinion", "Evidence", "Truth"], c: 1 },
  { t: "The Region Of South Asia Comprises ______ Countries.", o: ["6", "7", "8", "9"], c: 2 },
  { t: "An Area Of Land That Shares Common Features Is Called A ______.", o: ["Continent", "Region", "Country", "State"], c: 1 },
  { t: "The North, North-West And North-East Of South Asia Are Surrounded By ______.", o: ["Oceans", "Deserts", "Mountain Ranges", "Plains"], c: 2 },
  { t: "To The South Of Pakistan Lies The ______.", o: ["Bay Of Bengal", "Arabian Sea", "Indian Ocean", "Red Sea"], c: 1 },
  { t: "South Asia Is A Region Because It Shares The Following Characteristics: ______, ______ And ______.", o: ["Land, People, Culture", "Mountains, Rivers, Deserts", "Religion, Language, Food", "Climate, Economy, Government"], c: 0 },
  { t: "The Largest Continent Of The World Both In Area And Population Is ______.", o: ["Africa", "Asia", "Europe", "North America"], c: 1 },
  { t: "Asia Is ______ Of The Land Of The World.", o: ["One-Fourth", "One-Third", "One-Half", "Two-Thirds"], c: 1 },
  { t: "Approximately ______ Percent Of The World's Population Lives In Asia.", o: ["50", "60", "70", "80"], c: 1 },
  { t: "The Maldives Consists Of A Chain Of ______.", o: ["Mountains", "Islands", "Deserts", "Forests"], c: 1 },
  { t: "When Rocks Bend In Up-Folds And Down-Folds ______ Mountains Are Formed.", o: ["Block", "Fold", "Volcanic", "Dome"], c: 1 },
  { t: "When The Plates Move Towards Each Other And Do Not Fold But Crack ______ Mountains Are Formed.", o: ["Fold", "Fault-Block", "Volcanic", "Dome"], c: 1 },
  { t: "When Lava Flows To The Earth's Surface Causing A Cone-Shaped Mountain Called A ______.", o: ["Plateau", "Mountain", "Volcano", "Hill"], c: 2 },
  { t: "Plains Are Formed By ______ Or ______.", o: ["Folding, Faulting", "Erosion, Deposition", "Volcanic, Glacial", "Wind, Water"], c: 1 },
  { t: "The Three Large Plains In South Asia Are ______, ______ And ______.", o: ["Indus, Ganges, Brahmaputra", "Indus, Ganges, Nile", "Ganges, Brahmaputra, Yangtze", "Indus, Brahmaputra, Mekong"], c: 0 },
  { t: "Mount Everest, The Highest Mountain Peak In The World Lies In The ______.", o: ["Karakoram", "Himalayas", "Hindukush", "Andes"], c: 1 },
  { t: "The Second Highest Peak K-2 Is Situated In Which Mountain Range?", o: ["Himalayas", "Karakoram", "Hindukush", "Andes"], c: 1 },
  { t: "The Three Main Plateaus In South Asia Are ______, ______ And ______.", o: ["Deccan, Potwar, Balochistan", "Tibetan, Deccan, Potwar", "Balochistan, Deccan, Tibetan", "Potwar, Balochistan, Tibetan"], c: 0 },
  { t: "The Deccan Plateau Is Located In Which Country?", o: ["Pakistan", "India", "Nepal", "Bangladesh"], c: 1 },
  { t: "The Potwar Plateau Is Situated Between The River Indus And ______.", o: ["Jhelum", "Chenab", "Ravi", "Sutlej"], c: 0 },
  { t: "The Majority Of The Population Of Pakistan Lives In The ______ Areas.", o: ["Mountain", "Plateau", "Plain", "Desert"], c: 2 },
  { t: "The People Of Nepal Are Called ______.", o: ["Nepalese", "Nepali", "Nepalis", "Gurkhas"], c: 0 },
  { t: "The Two Main Ethnic Groups In Sri Lanka Are ______ And ______.", o: ["Sinhalese, Tamils", "Sinhalese, Bengalis", "Tamils, Bhotia", "Tamils, Gurungs"], c: 0 },
  { t: "The Majority Of The People Of Pakistan Are ______.", o: ["Hindus", "Christians", "Muslims", "Buddhists"], c: 2 },
  { t: "About ______ Percent Of The People Of Maldives Engage In Fishing.", o: ["60", "70", "80", "90"], c: 2 },
  { t: "The Maldives Consists Of A Group Of ______.", o: ["Islands", "Mountains", "Deserts", "Forests"], c: 0 },
  { t: "The Official Languages Of India Are Hindi And ______.", o: ["Urdu", "English", "Bengali", "Tamil"], c: 1 },
  { t: "About ______ Percent Of Indians Are Hindus.", o: ["73", "78", "83", "88"], c: 2 },
  { t: "Bangladesh Became An Independent Country In ______.", o: ["1947", "1956", "1971", "1973"], c: 2 },
  { t: "The Language Of The People Of Maldives (Dhivehi) Is Very Close To Which Language?", o: ["Hindi", "Tamil", "Sinhalese", "Bengali"], c: 2 },
  { t: "The Dominant Religion In Maldives Today Is ______.", o: ["Buddhism", "Hinduism", "Islam", "Christianity"], c: 2 },
  { t: "Sri Lanka Was Formerly Known As ______.", o: ["Serendip", "Ceylon", "Lanka", "Singhala"], c: 1 },
  { t: "The Activities That Use The Earth's Resources Such As Land, Water And Minerals Are ______ Activities.", o: ["Primary", "Secondary", "Tertiary", "Quaternary"], c: 0 },
  { t: "______ Activities Use Raw Materials And Change Them Into Valuable Products.", o: ["Primary", "Secondary", "Tertiary", "Quaternary"], c: 1 },
  { t: "______ Activities Refer To Segments Of The Economy That Provide Services.", o: ["Primary", "Secondary", "Tertiary", "Quaternary"], c: 2 },
  { t: "The Oil Is Bleached And Cleaned Using ______ In The Production Of Edible Cooking Oil.", o: ["Water", "Soap", "Chemicals", "Heat"], c: 1 },
  { t: "Banks Provide At Least Three Main Services: Saving, Lending And ______.", o: ["Investing", "Transfers Of Money", "Insurance", "Financial Advice"], c: 1 },
  { t: "A Place That Is Too Crowded Is Called ______.", o: ["Densely Populated", "Sparsely Populated", "Over-Populated", "Under-Populated"], c: 2 },
  { t: "If An Area Has Fewer People Living Than The Area Available, We Call This ______.", o: ["Densely Populated", "Sparsely Populated", "Over-Populated", "Moderately Populated"], c: 1 },
  { t: "Population Density Is Expressed As ______.", o: ["Persons Per Km²", "Persons Per Mile²", "Persons Per Hectare", "Persons Per Acre"], c: 0 },
  { t: "The Way People Are Spread Over An Area Is Called ______.", o: ["Population Density", "Population Distribution", "Population Growth", "Population Control"], c: 1 },
  { t: "The Number Of People Living In An Area Is Called ______.", o: ["Community", "Population", "Society", "Nation"], c: 1 },
  { t: "Positive Factors That Encourage People To Live In Certain Areas Include Access To ______, ______ And ______.", o: ["Water, Food, Employment", "Mountains, Forests, Deserts", "Cold, Snow, Ice", "Heat, Sand, Rocks"], c: 0 },
  { t: "In 2015, Pakistan's Population Was Approximately ______ Million.", o: ["150", "175", "200", "225"], c: 2 },
  { t: "The Birth Rate Is The Number Of Live Births For Every ______ People In A Year.", o: ["100", "500", "1000", "5000"], c: 2 },
  { t: "The Death Rate Is The Number Of Deaths For Every ______ People In A Year.", o: ["100", "500", "1000", "5000"], c: 2 },
  { t: "People Who Study Population Are Called ______.", o: ["Geographers", "Demographers", "Sociologists", "Anthropologists"], c: 1 },
  { t: "By 2050, The Total Population Of The World May Grow To Nearly ______ Billion.", o: ["5", "7", "10", "12"], c: 2 },
  { t: "The Fastest Growth In Population Is In The World's ______ Countries.", o: ["Rich", "Poor", "Developed", "Industrialized"], c: 1 },
  { t: "The Main Cause For The Rapid Growth Of The World Population Is The Drop In ______.", o: ["Birth Rates", "Death Rates", "Migration Rates", "Fertility Rates"], c: 1 },
  { t: "Over-Population Is The Number Of People In An Area That Exceeds The ______.", o: ["Capacity Of The Environment", "Available Food", "Housing Supply", "Water Supply"], c: 0 },
  { t: "One Of The Consequences Of Over-Population Easiest To See In Our Daily Life Is ______.", o: ["Crowding", "Pollution", "Unemployment", "Poverty"], c: 0 },
  { t: "China's Famous Policy To Control Growing Population Is The ______ Policy.", o: ["One-Child", "Two-Child", "Three-Child", "No-Child"], c: 0 },
  { t: "Educating ______ Is One Way In Which Governments Can Work To Reduce Population Growth.", o: ["Boys", "Girls", "Adults", "Elders"], c: 1 },
  { t: "Our Wants Are ______ But Our Resources Are ______.", o: ["Limited, Unlimited", "Unlimited, Limited", "Limited, Limited", "Unlimited, Unlimited"], c: 1 },
  { t: "People Cannot Have All The Goods And Services They Want So They Must Make ______.", o: ["Choices", "Decisions", "Plans", "Investments"], c: 0 },
  { t: "The Choices People Make Are Based On ______, ______ And ______.", o: ["Income, Cost, Values", "Wants, Needs, Desires", "Time, Money, Skills", "Family, Friends, Society"], c: 0 },
  { t: "The Requirements Which Are Necessary For Survival Are Called ______.", o: ["Wants", "Needs", "Desires", "Luxuries"], c: 1 },
  { t: "The Desires That Are Not Essential For Survival Are Called ______.", o: ["Needs", "Wants", "Necessities", "Requirements"], c: 1 },
  { t: "The Condition Of Not Being Able To Have All The Goods And Services That We Want Is Called ______.", o: ["Choice", "Scarcity", "Opportunity Cost", "Trade-Off"], c: 1 },
  { t: "Income Is The Money Received On A Regular Basis For ______.", o: ["Work", "Investment", "Saving", "Spending"], c: 0 },
  { t: "The Things Or Objects Which We Can Feel And Touch Are Called ______.", o: ["Services", "Goods", "Desires", "Needs"], c: 1 },
  { t: "Activities People Do In Their Free Time For Relaxation Or Enjoyment Are Called ______.", o: ["Work", "Leisure Activities", "Chores", "Duties"], c: 1 },
  { t: "We Must Make Choices Because We Face ______.", o: ["Scarcity", "Abundance", "Wealth", "Opportunity"], c: 0 },
  { t: "The Process Of Choosing And Best Allocating Limited Time And Money Is Called Making A ______.", o: ["Decision", "Trade-Off", "Choice", "Plan"], c: 1 },
  { t: "A Graph That Shows The Trade-Offs That Necessarily Accompany Decision-Making In The Face Of Scarcity Is Called The ______.", o: ["PPF", "PFF", "FPP", "PFP"], c: 0 },
  { t: "Benefit Is What You ______ From Something.", o: ["Give Up", "Gain", "Lose", "Sacrifice"], c: 1 },
  { t: "Cost Is What You Must ______ To Get Something.", o: ["Gain", "Give Up", "Pay", "Sacrifice"], c: 1 },
  { t: "The Act Of Balancing Two Things That Are Opposed To Each Other Is Called A ______.", o: ["Choice", "Trade-Off", "Decision", "Option"], c: 1 },
  { t: "PPF Stands For ______.", o: ["Production Possibility Frontier", "Product Performance Factor", "Production Process Flow", "Product Price Formula"], c: 0 },
  { t: "Y = C + S Means ______.", o: ["Income = Consumption + Saving", "Yield = Cost + Sales", "Year = Capital + Supply", "Yield = Consumption + Supply"], c: 0 },
  { t: "______ Is The Value Of The Next Best Alternative That Could Have Been Chosen.", o: ["Opportunity Cost", "Trade-Off", "Scarcity", "Choice"], c: 0 },
  { t: "If There Is No Opportunity Cost In Consuming A Good, We Call It A ______ Good.", o: ["Public", "Private", "Free", "Merit"], c: 2 },
  { t: "People Who Use Goods And Services To Satisfy Their Personal Needs And Wants Are Known As ______.", o: ["Producers", "Consumers", "Entrepreneurs", "Workers"], c: 1 },
  { t: "People And Firms That Use Resources To Make Goods And Services Are Known As ______.", o: ["Consumers", "Producers", "Entrepreneurs", "Workers"], c: 1 },
  { t: "A Business Person Who Uses A Shop To Run A Books And Stationery Business Cannot Use The Same Shop To Produce Pizzas. This Is An Example Of ______.", o: ["Scarcity", "Choice", "Opportunity Cost", "Trade-Off"], c: 2 },
  { t: "The Opportunity Cost Of Moving From Point B To Point A In A PPF Graph Shows ______.", o: ["What Is Gained", "What Is Sacrificed", "Total Production", "Maximum Output"], c: 1 },
  { t: "The Two Characteristics That Help Us To Decide Whether A Good Or Service Is Public Or Private Are ______ And ______.", o: ["Rivalry, Excludability", "Price, Quality", "Demand, Supply", "Quantity, Quality"], c: 0 },
  { t: "The Goods And Services Which Are Provided Free By The Government To Benefit The Society Are Known As ______ Goods.", o: ["Private", "Public", "Merit", "Collective"], c: 1 },
  { t: "Goods Which Are Used To Produce Other Goods And Services Are Known As ______ Goods.", o: ["Consumer", "Capital", "Public", "Private"], c: 1 },
  { t: "Things Or Objects We Buy To Satisfy Our Needs And Wants Are Called ______.", o: ["Services", "Goods", "Commodities", "Products"], c: 1 },
  { t: "Something (Some Work Or Some Action) Done For Us That We Pay For Is Called A ______.", o: ["Good", "Service", "Product", "Commodity"], c: 1 },
  { t: "Land, Buildings And Machinery Are Examples Of ______ Goods.", o: ["Consumer", "Capital", "Public", "Private"], c: 1 },
  { t: "Pencils, Books, And Toys Are Examples Of ______ Goods.", o: ["Consumer", "Capital", "Public", "Private"], c: 0 },
  { t: "Goods And Services Which Are Consumed Collectively, By Everyone Are Called ______.", o: ["Private Goods", "Collective Goods", "Merit Goods", "Capital Goods"], c: 1 },
  { t: "Roads, Parks, Schools, Libraries And Street Lighting Are Examples Of ______ Goods.", o: ["Private", "Public", "Consumer", "Capital"], c: 1 },
  { t: "A Single Business Is Known As A ______.", o: ["Firm", "Industry", "Company", "Enterprise"], c: 0 },
  { t: "A Group Of Businesses Or Producers That Produce A Similar Good Or Service Is Known As An ______.", o: ["Firm", "Industry", "Company", "Enterprise"], c: 1 },
  { t: "The Businesses That Are Owned By The Government And Run Like Private Sector Businesses, With A View To Make A Profit Are Known As ______.", o: ["Private Enterprises", "State-Owned Enterprises", "Public Enterprises", "Voluntary Organizations"], c: 1 },
  { t: "Voluntary Organizations Are Sometimes Known As ______.", o: ["Profit Organizations", "Non-Profit Organizations", "Public Organizations", "Government Organizations"], c: 1 },
  { t: "The Main Goal Of Private Sector Producers Is To Make A ______.", o: ["Profit", "Loss", "Service", "Contribution"], c: 0 },
  { t: "The Edhi Foundation Is An Example Of A ______.", o: ["Private Business", "State-Owned Enterprise", "Voluntary Organization", "Public Sector Business"], c: 2 },
  { t: "Bata Shoes Is An Example Of A ______.", o: ["Firm", "Industry", "State-Owned Enterprise", "Voluntary Organization"], c: 0 },
  { t: "The Textile Industry Is An Example Of An ______.", o: ["Firm", "Industry", "Company", "Enterprise"], c: 1 },
  { t: "A Tax Paid On The Money That A Person Or Business Receives As Income Is Known As ______ Tax.", o: ["Sales", "Income", "Property", "Excise"], c: 1 },
  { t: "A Tax That Is Added To The Price Of Goods And Services Is Known As ______ Tax.", o: ["Income", "Sales", "Property", "Excise"], c: 1 },
  { t: "Productive Resources In Economics Are Known As Factors Of ______.", o: ["Production", "Consumption", "Distribution", "Exchange"], c: 0 },
  { t: "A Person Who Comes Up With New Ideas About What And How To Produce, Makes Business Decisions And Bears The Risks Is Known As An ______.", o: ["Employee", "Entrepreneur", "Manager", "Worker"], c: 1 },
  { t: "Land Earns ______.", o: ["Wages", "Rent", "Interest", "Profit"], c: 1 },
  { t: "Labour Earns ______.", o: ["Wages", "Rent", "Interest", "Profit"], c: 0 },
  { t: "Capital Earns ______.", o: ["Wages", "Rent", "Interest", "Profit"], c: 2 },
  { t: "Entrepreneur Earns ______.", o: ["Wages", "Rent", "Interest", "Profit"], c: 3 },
  { t: "The Four Factors Of Production Are ______, ______, ______ And ______.", o: ["Land, Labour, Capital, Entrepreneur", "Land, Money, Resources, Technology", "People, Machines, Buildings, Money", "Nature, Work, Finance, Ideas"], c: 0 },
  { t: "The Language Spoken In Bhutan Is ______.", o: ["Hindi", "Nepalese", "Sharchhopka", "Urdu"], c: 2 },
  { t: "The Main Festival Of Nepal Is ______.", o: ["Eid", "Holi", "Dashain", "Diwali"], c: 2 },
  { t: "The Most Practiced Religions Of South Asia Are ______ And ______.", o: ["Islam, Hinduism", "Buddhism, Christianity", "Sikhism, Jainism", "Judaism, Zoroastrianism"], c: 0 },
  { t: "A Community Is A Social Unit Of Any Size That Shares Common ______.", o: ["Values", "Wealth", "Power", "Resources"], c: 0 },
  { t: "A Person's Sense Of Responsibilities, Ethics And Morals Is Influenced By ______.", o: ["Family And Culture", "Weather And Climate", "Technology And Media", "Politics And Economy"], c: 0 },
  { t: "In South Asia, ______ Are The Heads Of The Family Who Take Major Decisions For The Family.", o: ["Children", "Grandparents", "Mothers", "Uncles"], c: 1 },
  { t: "Girls Are Not Encouraged To Move Freely At Night In South Asia Is An Example Of A ______.", o: ["Value", "Norm", "Belief", "Tradition"], c: 1 },
  { t: "Respecting Elders And Being Polite To Them Is An Example Of A ______.", o: ["Value", "Norm", "Belief", "Tradition"], c: 0 },
  { t: "It Is Disrespectful To Use The Left Hand To Give And Take In South Asian Countries. This Is An Example Of A ______.", o: ["Value", "Norm", "Belief", "Custom"], c: 3 },
  { t: "A Fairly Flat Piece Of Lowland Is Called A ______.", o: ["Plain", "Plateau", "Mountain", "Valley"], c: 0 },
  { t: "The Lowland Between Two Highlands Is Called A ______.", o: ["Plain", "Plateau", "Mountain", "Valley"], c: 3 },
  { t: "A Highland With A Broad Base, Steep Slopes And A Narrow Top Is Called A ______.", o: ["Plain", "Plateau", "Mountain", "Hill"], c: 2 },
  { t: "A Highland That Is Flat On The Top Is Called A ______.", o: ["Plain", "Plateau", "Mountain", "Valley"], c: 1 },
  { t: "Saudi Arabia Has A ______ Form Of Government.", o: ["Democratic", "Monarchy", "Presidential", "Parliamentary"], c: 1 },
  { t: "Chandragupta Maurya founded the Mauryan Empire in ______ BCE.", o: ["350", "322", "300", "280"], c: 1 },
  { t: "Chandragupta Maurya's grandson was ______.", o: ["Bindusara", "Ashoka", "Kautilya", "Alexander"], c: 1 },
  { t: "The Mauryan Empire lasted about ______ years.", o: ["100", "130", "140", "150"], c: 2 },
  { t: "Ashoka became king at around ______ BC.", o: ["300", "272", "269", "232"], c: 2 },
  { t: "Ashoka's Empire included much of ______.", o: ["China", "India", "Persia", "Egypt"], c: 1 },
  { t: "The Persian Empire was founded in the year ______.", o: ["550 BC", "539 BC", "522 BC", "500 BC"], c: 0 },
  { t: "The famous road made by Darius is known as ______.", o: ["Silk Road", "Royal Road", "Grand Trunk Road", "Persian Road"], c: 1 },
  { t: "The religion that gave the answers of the questions which people have for their problems was ______.", o: ["Buddhism", "Zoroastrianism", "Hinduism", "Christianity"], c: 1 },
  { t: "Ansan tribal kingdom lived under the rule of another Iranian ruler named ______.", o: ["Darius", "Cyrus", "Xerxes", "Cambyses"], c: 1 },
  { t: "The Middle Ages dates from ______ to ______.", o: ["400, 1400", "450, 1450", "500, 1500", "550, 1550"], c: 1 },
  { t: "Dark Age is referred to ______.", o: ["early Middle Ages", "late Middle Ages", "Renaissance", "Industrial Revolution"], c: 0 },
  { t: "Crusades mean ______.", o: ["holy wars", "trade routes", "religious festivals", "political alliances"], c: 0 },
  { t: "Feudal system refers to ______.", o: ["economic system", "social hierarchy", "political organization", "military structure"], c: 1 },
  { t: "Plague is a disease that brought ______ to Europe.", o: ["prosperity", "death", "peace", "wealth"], c: 1 },
  { t: "______ is a basic and fundamental law of a state.", o: ["Constitution", "Law", "Act", "Charter"], c: 0 },
  { t: "The representative government is consisted of three branches i.e. Executive, ______ and ______.", o: ["Legislative, Judicial", "Federal, Provincial", "Senate, Assembly", "Upper, Lower"], c: 0 },
  { t: "Sovereignty means ______.", o: ["supreme authority", "democracy", "independence", "freedom"], c: 0 },
  { t: "The constitution of Pakistan comprises of ______ articles.", o: ["200", "250", "280", "300"], c: 2 },
  { t: "The civil rights are mainly associated with the life and ______ of a citizen.", o: ["liberty", "property", "security", "health"], c: 0 },
  { t: "The Article 25-A of the Constitution provides for ______ to all children of age five (5) to sixteen (16).", o: ["free education", "free health", "free food", "free housing"], c: 0 },
  { t: "The fundamental rights promote better life, ______ and ______.", o: ["equality, justice", "freedom, security", "peace, harmony", "progress, development"], c: 0 },
  { t: "The person who works for an organization without being paid is called ______.", o: ["worker", "volunteer", "employee", "servant"], c: 1 },
  { t: "Basic role of civil society is to limit and control the power of the ______.", o: ["state", "government", "parliament", "judiciary"], c: 0 },
  { t: "The volunteer sector plays a key role in ______.", o: ["society", "economy", "politics", "culture"], c: 0 },
  { t: "Civil society can provide a training ground for future political ______.", o: ["leaders", "workers", "thinkers", "activists"], c: 0 },
  { t: "The land size of Asia is ______.", o: ["17,212,000 sq miles", "17,212,000 sq km", "16,212,000 sq miles", "18,212,000 sq miles"], c: 0 },
  { t: "The coastline of Asia is ______ long.", o: ["50,000 km", "55,000 km", "62,800 km", "70,000 km"], c: 2 },
  { t: "Ural is the name of ______.", o: ["a mountain", "a river", "a desert", "a plateau"], c: 0 },
  { t: "Arabian peninsula is situated between ______ and ______.", o: ["Red Sea, Persian Gulf", "Indian Ocean, Arabian Sea", "Mediterranean, Black Sea", "Caspian Sea, Red Sea"], c: 0 },
  { t: "Karakoram Range is located in ______ and ______.", o: ["Pakistan, China", "India, Nepal", "Afghanistan, Tajikistan", "China, India"], c: 0 },
  { t: "The two most populous countries of the world i.e China and ______ are part of Asia.", o: ["India", "Pakistan", "Bangladesh", "Indonesia"], c: 0 },
  { t: "The major crop grown in Bangladesh is ______.", o: ["wheat", "rice", "jute", "tea"], c: 2 },
  { t: "Borneo is located in ______.", o: ["Indonesia", "Malaysia", "Philippines", "Thailand"], c: 1 },
  { t: "The capital city of Malaysia is ______.", o: ["Jakarta", "Kuala Lumpur", "Singapore", "Bangkok"], c: 1 },
  { t: "______ is a process of removing salt from substance.", o: ["Desalination", "Evaporation", "Condensation", "Filtration"], c: 0 },
  { t: "The process where water turns into water vapors is called ______.", o: ["condensation", "evaporation", "precipitation", "transpiration"], c: 1 },
  { t: "The process where water runs over the surface of the earth is known as ______.", o: ["runoff", "infiltration", "evaporation", "condensation"], c: 0 },
  { t: "There are three major water sources in Pakistan i.e. rain water, ______ and rivers.", o: ["ground water", "lake water", "sea water", "canal water"], c: 0 },
  { t: "______ is the man-made supply of water to the land to encourage vegetation.", o: ["Irrigation", "Drainage", "Cultivation", "Fertilization"], c: 0 },
  { t: "Weathering is a process in which ______.", o: ["rocks break down", "soil erodes", "water evaporates", "plants grow"], c: 0 },
  { t: "______ is the shift from rural to urban life.", o: ["Globalization", "Urbanization", "Education", "Desertification"], c: 1 },
  { t: "A single urban centre that leads all others in attracting people, resources and money is a ______.", o: ["Megalopolis", "Growth pole", "Primate City", "Shanty town"], c: 2 },
  { t: "The population in Southeast Asia is concentrated in ______.", o: ["River valleys and coastal plains", "Mountains", "Plateaus", "Deserts"], c: 0 },
  { t: "When the price goes up, the quantity demanded goes ______.", o: ["up", "down", "remains same", "uncertain"], c: 1 },
  { t: "Two basic types of demand are ______ and ______.", o: ["individual, market", "primary, secondary", "elastic, inelastic", "high, low"], c: 0 },
  { t: "The graphical representation of demand schedule is known as a ______.", o: ["demand curve", "supply curve", "line graph", "pie chart"], c: 0 },
  { t: "A person who creates economic value or produces goods and services is called a ______.", o: ["producer", "consumer", "seller", "buyer"], c: 0 },
  { t: "If there is a technological advancement in a good's production, its supply would be ______.", o: ["increase", "decrease", "remain same", "uncertain"], c: 0 },
  { t: "A ______ represents the relationship between the price of a good or service and the quantity supplied through a graph.", o: ["supply curve", "demand curve", "line graph", "bar graph"], c: 0 },
  { t: "A democratic leader is one who ______ the people in the decision making process.", o: ["involves", "excludes", "ignores", "avoids"], c: 0 },
  { t: "The autocratic leaders make decisions without any ______ of others.", o: ["input", "support", "approval", "consent"], c: 0 },
  { t: "The society is naturally divided into ______ and ______.", o: ["leaders, followers", "rich, poor", "young, old", "educated, uneducated"], c: 0 },
  { t: "Women have a role to play as a ______ in every society.", o: ["nation builder", "housewife", "mother", "worker"], c: 0 },
  { t: "Countries are producing a huge quantity of graduates but they lack basic skills and ______.", o: ["training", "education", "knowledge", "experience"], c: 0 },
  { t: "People cut the trees and destroy forests for getting ______ and ______.", o: ["land, accommodating people", "wood, fuel", "money, profit", "agriculture, settlement"], c: 0 },
  { t: "According to international standard, an individual who is of ______ age has right to cast his/her vote in the elections.", o: ["16", "18", "21", "25"], c: 1 },
  { t: "When a child reaches at the age of schooling then, he/she can exercise his/her right to ______.", o: ["education", "health", "work", "play"], c: 0 },
  { t: "A minority can be of race, religion and ______ in any society.", o: ["ethnicity", "gender", "age", "class"], c: 0 },
  { t: "Political parties identify and articulate the ______ of people and develop manifestoes accordingly.", o: ["interests", "problems", "demands", "needs"], c: 0 },
  { t: "Taking photographs of the ground from an elevated position is called ______.", o: ["aerial photography", "satellite imagery", "remote sensing", "cartography"], c: 0 },
  { t: "The skills in which the specific ways students are expected to behave in order to achieve class norms are called ______.", o: ["collaborative skills", "leadership skills", "communication skills", "problem-solving skills"], c: 0 },
  { t: "The process of making choices by identifying a decision, gathering information and assessing alternative resolutions is called ______.", o: ["decision-making", "problem-solving", "critical thinking", "collaboration"], c: 0 },
  { t: "The way of representing statistical data using symbolic figures to match the frequencies of different kinds of data is called ______.", o: ["pictograph", "bar graph", "line graph", "pie chart"], c: 0 },
  { t: "The two kinds of bar graph are ______ and ______.", o: ["vertical, horizontal", "simple, complex", "single, double", "primary, secondary"], c: 0 },
  { t: "Victimized person should tell about the incident to someone he/she ______ the most.", o: ["trusts", "loves", "respects", "believes"], c: 0 },
  { t: "Protection from violence is every individual's ______.", o: ["right", "duty", "privilege", "responsibility"], c: 0 },
  { t: "Revenue is calculated by multiplying ______ by ______.", o: ["price, quantity", "cost, profit", "income, expense", "demand, supply"], c: 0 },
  { t: "Total Profit = ______ - ______.", o: ["Total Revenue, Total Costs", "Total Income, Total Expenses", "Total Sales, Total Purchase", "Total Demand, Total Supply"], c: 0 },
  { t: "A supply schedule is a table which shows how much one or more firms will be willing to supply at ______.", o: ["particular prices", "any price", "varying prices", "maximum prices"], c: 0 },
  { t: "The supply curve is a graphical representation of the ______.", o: ["supply schedule", "demand schedule", "market equilibrium", "production function"], c: 0 },
  { t: "Private goods are characterized by ______ and ______.", o: ["rivalry, excludability", "non-rivalry, non-excludability", "public, private", "consumer, capital"], c: 0 },
  { t: "Public goods are characterized by ______ and ______.", o: ["non-rivalry, non-excludability", "rivalry, excludability", "private, public", "free, paid"], c: 0 },
  { t: "Income tax is a tax paid on the ______ that a person or business receives.", o: ["money", "goods", "services", "property"], c: 0 },
  { t: "Sales tax is a tax added to the ______ of goods and services.", o: ["price", "quantity", "quality", "demand"], c: 0 },
  { t: "Pakistan has a ______ form of government.", o: ["federal parliamentary", "federal presidential", "unitary parliamentary", "unitary presidential"], c: 0 },
  { t: "The 1973 Constitution of Pakistan has been amended ______ times so far.", o: ["20", "23", "25", "28"], c: 1 },
  { t: "The National Language of Pakistan is ______.", o: ["Urdu", "English", "Punjabi", "Sindhi"], c: 0 },
  { t: "The Official Language of Pakistan is ______.", o: ["English", "Urdu", "Punjabi", "Sindhi"], c: 0 },
  { t: "The Chairman of Senate is elected for a term of ______ years.", o: ["2", "3", "4", "5"], c: 1 },
  { t: "The Speaker of the National Assembly is elected from amongst its ______.", o: ["members", "senators", "judges", "ministers"], c: 0 },
  { t: "The four provinces of Pakistan are ______, ______, ______ and ______.", o: ["Punjab, Sindh, KPK, Balochistan", "Punjab, Sindh, Balochistan, FATA", "Sindh, KPK, Balochistan, Gilgit", "Punjab, Sindh, KPK, Gilgit"], c: 0 },
  { t: "Pakistan came into existence in ______.", o: ["1945", "1947", "1948", "1949"], c: 1 },
  { t: "Water covers about ______ percent of the earth's surface.", o: ["65", "70", "75", "80"], c: 2 },
  { t: "In oceans, ______ of water is too salty for people, animals or plants to use.", o: ["95", "96", "97", "98"], c: 2 },
  { t: "Only ______ of water is fresh water but not all of it can be used.", o: ["0.5%", "1%", "2%", "3%"], c: 1 },
  { t: "Ground water is generally found around ______ feet deep in the Earth.", o: ["1,000", "1,500", "2,000", "2,500"], c: 2 },
  { t: "In Pakistan, ______ percent of agricultural land is under irrigation.", o: ["65", "70", "75", "80"], c: 2 },
  { t: "The average annual flow of Pakistan's Rivers is approximately ______ million acre feet (MAF).", o: ["120", "135", "142", "150"], c: 2 },
  { t: "About ______ MAF of water is diverted for irrigation purposes in Pakistan.", o: ["95", "100", "104", "110"], c: 2 },
  { t: "Ground water provides approximately ______ percent of crop water requirements in Pakistan.", o: ["30", "35", "40", "45"], c: 2 },
  { t: "Water logging and salinity has affected about ______ million hectares of agricultural land in Pakistan.", o: ["2.5", "3.0", "3.5", "4.0"], c: 2 },
  { t: "A person who is a legally recognized resident of a particular country is called a ______.", o: ["citizen", "resident", "national", "subject"], c: 0 },
  { t: "Natural-born citizen is a citizen who was ______ in a state.", o: ["born", "adopted", "naturalized", "settled"], c: 0 },
  { t: "Naturalized citizen is one who has adopted the citizenship of any other ______.", o: ["state", "country", "nation", "region"], c: 0 },
  { t: "The Ulema were the religious scholars who were experts in the ______ law.", o: ["Sharia", "Common", "Civil", "Constitutional"], c: 0 },
  { t: "The non-Muslim communities in the Ottoman Empire were called ______.", o: ["millets", "dhimmi", "minorities", "foreigners"], c: 0 },
  { t: "The Ottoman Sultan also claimed to be a ______.", o: ["caliph", "king", "emperor", "ruler"], c: 0 },
  { t: "The chief minister of the Ottoman Empire was called the ______.", o: ["Grand Vizier", "Sultan", "Caliph", "Amir"], c: 0 },
  { t: "The Ottoman Empire lasted till the beginning of ______.", o: ["World War I", "World War II", "French Revolution", "Industrial Revolution"], c: 0 },
  { t: "The Umayyad dynasty ruled from ______ until 750 AD.", o: ["600", "650", "661", "700"], c: 2 },
  { t: "The Abbasid dynasty ruled until ______ AD.", o: ["1158", "1200", "1250", "1258"], c: 3 },
  { t: "Al-Khwarazmi discovered the number ______.", o: ["one", "two", "zero", "ten"], c: 2 },
  { t: "Ibrahim Al-Fazari invented a device known as the ______ for navigation.", o: ["astrolabe", "compass", "sextant", "telescope"], c: 0 },
  { t: "Ibn Sina's famous medical book is called ______.", o: ["Qanun fi-al-Tibb", "Kitab al-Shifa", "Canon of Medicine", "Al-Qanun"], c: 0 },
  { t: "The Battle of Manzikert was fought in ______ AD.", o: ["1050", "1071", "1095", "1100"], c: 1 },
  { t: "The Ottoman Empire captured Constantinople in ______ AD.", o: ["1400", "1453", "1492", "1500"], c: 1 },
  { t: "The Black Death occurred in ______ AD.", o: ["1300-1325", "1347-1348", "1350-1375", "1400-1425"], c: 1 },
  { t: "The first hospital in Paris was founded by Louis IX after he came back from Crusade in ______ AD.", o: ["1200", "1250", "1260", "1300"], c: 2 },
  { t: "The number of refugees in the world is approximately ______ million.", o: ["15.5", "17.5", "19.5", "21.5"], c: 2 },
  { t: "Together with internally displaced persons, there are ______ million refugees, asylum seekers and internally displaced persons.", o: ["49.5", "54.5", "59.5", "64.5"], c: 2 },
  { t: "Pakistan hosted the most refugees in 2008, with ______ million, nearly all from Afghanistan.", o: ["1.5", "1.8", "2.0", "2.2"], c: 1 },
  { t: "Up to ______ percent of all Afghan refugees live in Iran and Pakistan.", o: ["85", "90", "95", "96"], c: 3 },
  { t: "The term \"brain drain\" is used to indicate the drain of ______ persons from one country to another.", o: ["skilled", "unskilled", "educated", "qualified"], c: 0 },
  { t: "An asylum seeker is a person who has fled from his or her own country due to fear of ______.", o: ["torture", "poverty", "war", "natural disaster"], c: 0 },
  { t: "An internally displaced person is someone who is living inside the borders of their own country but is unable to safely live in their own ______.", o: ["home", "country", "region", "city"], c: 0 },
  { t: "The Afghan refugee population constitutes the largest extended ______ in the world.", o: ["situation", "crisis", "problem", "disaster"], c: 0 },
  { t: "People of FATA (Pakistan) were IDPs in the year ______.", o: ["2013-2014", "2014-2015", "2015-2016", "2016-2017"], c: 2 },
  { t: "The East Asia and Pacific countries were relatively peaceful in recent decades compared to ______.", o: ["Middle East, South Asia, Central Asia", "Europe, Africa, America", "North Asia, West Asia", "Southeast Asia, Southwest Asia"], c: 0 },
  { t: "Total membership of the National Assembly of Pakistan is ______.", o: ["272", "342", "342", "442"], c: 1 },
  { t: "Members of the National Assembly are elected for a term of ______ years.", o: ["4", "5", "6", "7"], c: 1 },
  { t: "The Senate of Pakistan has ______ members.", o: ["96", "100", "104", "108"], c: 2 },
  { t: "Term of members of the Senate is ______ years.", o: ["4", "5", "6", "7"], c: 2 },
  { t: "One-half of the Senate members retire after every ______ years.", o: ["2", "3", "4", "5"], c: 1 },
  { t: "The Sindh Local Govt Act was passed in ______.", o: ["2005", "2010", "2011", "2013"], c: 3 },
  { t: "The three tiers of local government under Sindh Local Govt Act are ______, ______ And ______.", o: ["District, Taluka, Union", "City, Town, Village", "Provincial, District, Taluka", "Union, Taluka, Town"], c: 0 },
  { t: "In metropolitan cities, the Chairman of local government is called ______.", o: ["Mayor", "Commissioner", "Administrator", "Deputy Commissioner"], c: 0 },
  { t: "Councilors in local government serve a term of ______ years.", o: ["3", "4", "5", "6"], c: 1 },
  { t: "The two houses of Pakistan's Parliament are ______ And ______.", o: ["National Assembly, Senate", "National Assembly, Provincial Assembly", "Senate, Provincial Assembly", "Lower House, Upper House"], c: 0 },
  { t: "The President of Pakistan is the Supreme Commander of the ______.", o: ["Armed Forces", "Civil Service", "Judiciary", "Parliament"], c: 0 },
  { t: "The Chief Justice of Pakistan is appointed by the President with the advice of the ______.", o: ["Prime Minister", "Senate", "National Assembly", "Chief Election Commissioner"], c: 0 },
  { t: "Kautilya wrote which book of rules to run the Empire?", o: ["Arthasastra", "Shastras", "Vedas", "Puranas"], c: 0 },
  { t: "Ashoka renounced warfare after which war?", o: ["Kalinga War", "Mahabharata War", "Mughal War", "Persian War"], c: 0 },
  { t: "The Mauryan Empire was divided into how many provinces?", o: ["2", "3", "4", "5"], c: 2 },
  { t: "The famous educational centers during Mauryan rule were ______, ______ And ______.", o: ["Taxila, Ujjayini, Varanasi", "Pataliputra, Taxila, Gaya", "Varanasi, Nalanda, Taxila", "Ujjayini, Nalanda, Pataliputra"], c: 0 }
];

async function seedPakStudies() {
  const client = new Client({ connectionString });
  await client.connect();
  console.log('✅ Connected to Neon DB for Pakistan Studies MCQs...');

  try {
    await client.query('BEGIN');

    for (let i = 0; i < pakStudiesQuestions.length; i++) {
      const q = pakStudiesQuestions[i];
      const qId = `pak-std-q-${i + 1}`;
      await client.query(`
        INSERT INTO "Question" (id, "textEn", "textUr", "optionsEn", "optionsUr", "correctIndex", subject, difficulty, "createdAt", "updatedAt")
        VALUES ($1, $2, $3, $4, $5, $6, 'Pakistan Studies', 'medium', NOW(), NOW())
        ON CONFLICT (id) DO UPDATE SET "textEn"=EXCLUDED."textEn", "optionsEn"=EXCLUDED."optionsEn", "correctIndex"=EXCLUDED."correctIndex", subject=EXCLUDED.subject
      `, [qId, q.t, q.t, q.o, q.o, q.c]);
    }

    await client.query('COMMIT');
    console.log(`🎉 SUCCESS! All ${pakStudiesQuestions.length} Pakistan Studies MCQs seeded into Neon DB!`);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌ Error during seeding:', err);
  } finally {
    await client.end();
  }
}

seedPakStudies().catch(console.error);
